// Code generated by ent, DO NOT EDIT.

package playerqueststate

import (
	"agentic-npc-backend/internal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLTE(FieldID, id))
}

// QuestIdentifier applies equality check predicate on the "quest_identifier" field. It's identical to QuestIdentifierEQ.
func QuestIdentifier(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldQuestIdentifier, v))
}

// CurrentStep applies equality check predicate on the "current_step" field. It's identical to CurrentStepEQ.
func CurrentStep(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldCurrentStep, v))
}

// IsCompleted applies equality check predicate on the "is_completed" field. It's identical to IsCompletedEQ.
func IsCompleted(v bool) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldIsCompleted, v))
}

// CompletionRate applies equality check predicate on the "completion_rate" field. It's identical to CompletionRateEQ.
func CompletionRate(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldCompletionRate, v))
}

// QuestIdentifierEQ applies the EQ predicate on the "quest_identifier" field.
func QuestIdentifierEQ(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldQuestIdentifier, v))
}

// QuestIdentifierNEQ applies the NEQ predicate on the "quest_identifier" field.
func QuestIdentifierNEQ(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNEQ(FieldQuestIdentifier, v))
}

// QuestIdentifierIn applies the In predicate on the "quest_identifier" field.
func QuestIdentifierIn(vs ...string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldIn(FieldQuestIdentifier, vs...))
}

// QuestIdentifierNotIn applies the NotIn predicate on the "quest_identifier" field.
func QuestIdentifierNotIn(vs ...string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNotIn(FieldQuestIdentifier, vs...))
}

// QuestIdentifierGT applies the GT predicate on the "quest_identifier" field.
func QuestIdentifierGT(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGT(FieldQuestIdentifier, v))
}

// QuestIdentifierGTE applies the GTE predicate on the "quest_identifier" field.
func QuestIdentifierGTE(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGTE(FieldQuestIdentifier, v))
}

// QuestIdentifierLT applies the LT predicate on the "quest_identifier" field.
func QuestIdentifierLT(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLT(FieldQuestIdentifier, v))
}

// QuestIdentifierLTE applies the LTE predicate on the "quest_identifier" field.
func QuestIdentifierLTE(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLTE(FieldQuestIdentifier, v))
}

// QuestIdentifierContains applies the Contains predicate on the "quest_identifier" field.
func QuestIdentifierContains(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldContains(FieldQuestIdentifier, v))
}

// QuestIdentifierHasPrefix applies the HasPrefix predicate on the "quest_identifier" field.
func QuestIdentifierHasPrefix(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldHasPrefix(FieldQuestIdentifier, v))
}

// QuestIdentifierHasSuffix applies the HasSuffix predicate on the "quest_identifier" field.
func QuestIdentifierHasSuffix(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldHasSuffix(FieldQuestIdentifier, v))
}

// QuestIdentifierEqualFold applies the EqualFold predicate on the "quest_identifier" field.
func QuestIdentifierEqualFold(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEqualFold(FieldQuestIdentifier, v))
}

// QuestIdentifierContainsFold applies the ContainsFold predicate on the "quest_identifier" field.
func QuestIdentifierContainsFold(v string) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldContainsFold(FieldQuestIdentifier, v))
}

// CurrentStepEQ applies the EQ predicate on the "current_step" field.
func CurrentStepEQ(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldCurrentStep, v))
}

// CurrentStepNEQ applies the NEQ predicate on the "current_step" field.
func CurrentStepNEQ(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNEQ(FieldCurrentStep, v))
}

// CurrentStepIn applies the In predicate on the "current_step" field.
func CurrentStepIn(vs ...int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldIn(FieldCurrentStep, vs...))
}

// CurrentStepNotIn applies the NotIn predicate on the "current_step" field.
func CurrentStepNotIn(vs ...int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNotIn(FieldCurrentStep, vs...))
}

// CurrentStepGT applies the GT predicate on the "current_step" field.
func CurrentStepGT(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGT(FieldCurrentStep, v))
}

// CurrentStepGTE applies the GTE predicate on the "current_step" field.
func CurrentStepGTE(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGTE(FieldCurrentStep, v))
}

// CurrentStepLT applies the LT predicate on the "current_step" field.
func CurrentStepLT(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLT(FieldCurrentStep, v))
}

// CurrentStepLTE applies the LTE predicate on the "current_step" field.
func CurrentStepLTE(v int) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLTE(FieldCurrentStep, v))
}

// IsCompletedEQ applies the EQ predicate on the "is_completed" field.
func IsCompletedEQ(v bool) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldIsCompleted, v))
}

// IsCompletedNEQ applies the NEQ predicate on the "is_completed" field.
func IsCompletedNEQ(v bool) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNEQ(FieldIsCompleted, v))
}

// CompletionRateEQ applies the EQ predicate on the "completion_rate" field.
func CompletionRateEQ(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldEQ(FieldCompletionRate, v))
}

// CompletionRateNEQ applies the NEQ predicate on the "completion_rate" field.
func CompletionRateNEQ(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNEQ(FieldCompletionRate, v))
}

// CompletionRateIn applies the In predicate on the "completion_rate" field.
func CompletionRateIn(vs ...float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldIn(FieldCompletionRate, vs...))
}

// CompletionRateNotIn applies the NotIn predicate on the "completion_rate" field.
func CompletionRateNotIn(vs ...float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldNotIn(FieldCompletionRate, vs...))
}

// CompletionRateGT applies the GT predicate on the "completion_rate" field.
func CompletionRateGT(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGT(FieldCompletionRate, v))
}

// CompletionRateGTE applies the GTE predicate on the "completion_rate" field.
func CompletionRateGTE(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldGTE(FieldCompletionRate, v))
}

// CompletionRateLT applies the LT predicate on the "completion_rate" field.
func CompletionRateLT(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLT(FieldCompletionRate, v))
}

// CompletionRateLTE applies the LTE predicate on the "completion_rate" field.
func CompletionRateLTE(v float32) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.FieldLTE(FieldCompletionRate, v))
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.PlayerQuestState {
	return predicate.PlayerQuestState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasQuest applies the HasEdge predicate on the "quest" edge.
func HasQuest() predicate.PlayerQuestState {
	return predicate.PlayerQuestState(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, QuestTable, QuestColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasQuestWith applies the HasEdge predicate on the "quest" edge with a given conditions (other predicates).
func HasQuestWith(preds ...predicate.Quest) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(func(s *sql.Selector) {
		step := newQuestStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerQuestState) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerQuestState) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerQuestState) predicate.PlayerQuestState {
	return predicate.PlayerQuestState(sql.NotPredicates(p))
}
