// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.31.1
// source: ai.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Static paths (the "key" for the Python agent)
	PersonalityPath string `protobuf:"bytes,1,opt,name=personality_path,json=personalityPath,proto3" json:"personality_path,omitempty"`
	BackstoryPath   string `protobuf:"bytes,2,opt,name=backstory_path,json=backstoryPath,proto3" json:"backstory_path,omitempty"`
	LorePath        string `protobuf:"bytes,3,opt,name=lore_path,json=lorePath,proto3" json:"lore_path,omitempty"`
	// Dynamic context (the "payload")
	SpeakerEmotions map[string]float32 `protobuf:"bytes,4,rep,name=speaker_emotions,json=speakerEmotions,proto3" json:"speaker_emotions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"` // how the NPC feels about the player it is speaking to
	GeneralMood     map[string]float32 `protobuf:"bytes,5,rep,name=general_mood,json=generalMood,proto3" json:"general_mood,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed32,2,opt,name=value"`             // how the NPC feels in general, all players together
	MemoryLines     []string           `protobuf:"bytes,11,rep,name=memory_lines,json=memoryLines,proto3" json:"memory_lines,omitempty"`                                                                                        // already ranked and worded by the Go orchestrator
	// Event details
	EventType        string  `protobuf:"bytes,6,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	QuestionText     string  `protobuf:"bytes,7,opt,name=question_text,json=questionText,proto3" json:"question_text,omitempty"`
	SourceEntityId   string  `protobuf:"bytes,8,opt,name=source_entity_id,json=sourceEntityId,proto3" json:"source_entity_id,omitempty"`
	CurrentQuestStep int32   `protobuf:"varint,9,opt,name=current_quest_step,json=currentQuestStep,proto3" json:"current_quest_step,omitempty"`
	CompletionRate   float32 `protobuf:"fixed32,10,opt,name=completion_rate,json=completionRate,proto3" json:"completion_rate,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EventRequest) Reset() {
	*x = EventRequest{}
	mi := &file_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventRequest) ProtoMessage() {}

func (x *EventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventRequest.ProtoReflect.Descriptor instead.
func (*EventRequest) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{0}
}

func (x *EventRequest) GetPersonalityPath() string {
	if x != nil {
		return x.PersonalityPath
	}
	return ""
}

func (x *EventRequest) GetBackstoryPath() string {
	if x != nil {
		return x.BackstoryPath
	}
	return ""
}

func (x *EventRequest) GetLorePath() string {
	if x != nil {
		return x.LorePath
	}
	return ""
}

func (x *EventRequest) GetSpeakerEmotions() map[string]float32 {
	if x != nil {
		return x.SpeakerEmotions
	}
	return nil
}

func (x *EventRequest) GetGeneralMood() map[string]float32 {
	if x != nil {
		return x.GeneralMood
	}
	return nil
}

func (x *EventRequest) GetMemoryLines() []string {
	if x != nil {
		return x.MemoryLines
	}
	return nil
}

func (x *EventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EventRequest) GetQuestionText() string {
	if x != nil {
		return x.QuestionText
	}
	return ""
}

func (x *EventRequest) GetSourceEntityId() string {
	if x != nil {
		return x.SourceEntityId
	}
	return ""
}

func (x *EventRequest) GetCurrentQuestStep() int32 {
	if x != nil {
		return x.CurrentQuestStep
	}
	return 0
}

func (x *EventRequest) GetCompletionRate() float32 {
	if x != nil {
		return x.CompletionRate
	}
	return 0
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActionType    string                 `protobuf:"bytes,1,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ActionResponse) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionResponse) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// TokenChunk is one frame of a streamed response (C3). Partial frames carry an
// incremental `text` delta with done=false; the final frame has done=true and the
// action_type (e.g. "SPEAK"). Consumers concatenate the deltas for the full content.
type TokenChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	Done          bool                   `protobuf:"varint,2,opt,name=done,proto3" json:"done,omitempty"`
	ActionType    string                 `protobuf:"bytes,3,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenChunk) Reset() {
	*x = TokenChunk{}
	mi := &file_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenChunk) ProtoMessage() {}

func (x *TokenChunk) ProtoReflect() protoreflect.Message {
	mi := &file_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenChunk.ProtoReflect.Descriptor instead.
func (*TokenChunk) Descriptor() ([]byte, []int) {
	return file_ai_proto_rawDescGZIP(), []int{2}
}

func (x *TokenChunk) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TokenChunk) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *TokenChunk) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

var File_ai_proto protoreflect.FileDescriptor

const file_ai_proto_rawDesc = "" +
	"\n" +
	"\bai.proto\x12\x02ai\"\x81\x05\n" +
	"\fEventRequest\x12)\n" +
	"\x10personality_path\x18\x01 \x01(\tR\x0fpersonalityPath\x12%\n" +
	"\x0ebackstory_path\x18\x02 \x01(\tR\rbackstoryPath\x12\x1b\n" +
	"\tlore_path\x18\x03 \x01(\tR\blorePath\x12P\n" +
	"\x10speaker_emotions\x18\x04 \x03(\v2%.ai.EventRequest.SpeakerEmotionsEntryR\x0fspeakerEmotions\x12D\n" +
	"\fgeneral_mood\x18\x05 \x03(\v2!.ai.EventRequest.GeneralMoodEntryR\vgeneralMood\x12!\n" +
	"\fmemory_lines\x18\v \x03(\tR\vmemoryLines\x12\x1d\n" +
	"\n" +
	"event_type\x18\x06 \x01(\tR\teventType\x12#\n" +
	"\rquestion_text\x18\a \x01(\tR\fquestionText\x12(\n" +
	"\x10source_entity_id\x18\b \x01(\tR\x0esourceEntityId\x12,\n" +
	"\x12current_quest_step\x18\t \x01(\x05R\x10currentQuestStep\x12'\n" +
	"\x0fcompletion_rate\x18\n" +
	" \x01(\x02R\x0ecompletionRate\x1aB\n" +
	"\x14SpeakerEmotionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\x1a>\n" +
	"\x10GeneralMoodEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x02R\x05value:\x028\x01\"K\n" +
	"\x0eActionResponse\x12\x1f\n" +
	"\vaction_type\x18\x01 \x01(\tR\n" +
	"actionType\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"U\n" +
	"\n" +
	"TokenChunk\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x12\n" +
	"\x04done\x18\x02 \x01(\bR\x04done\x12\x1f\n" +
	"\vaction_type\x18\x03 \x01(\tR\n" +
	"actionType2o\n" +
	"\aAIBrain\x12/\n" +
	"\x05Think\x12\x10.ai.EventRequest\x1a\x12.ai.ActionResponse\"\x00\x123\n" +
	"\vThinkStream\x12\x10.ai.EventRequest\x1a\x0e.ai.TokenChunk\"\x000\x01B\x12Z\x10./internal/protob\x06proto3"

var (
	file_ai_proto_rawDescOnce sync.Once
	file_ai_proto_rawDescData []byte
)

func file_ai_proto_rawDescGZIP() []byte {
	file_ai_proto_rawDescOnce.Do(func() {
		file_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)))
	})
	return file_ai_proto_rawDescData
}

var file_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ai_proto_goTypes = []any{
	(*EventRequest)(nil),   // 0: ai.EventRequest
	(*ActionResponse)(nil), // 1: ai.ActionResponse
	(*TokenChunk)(nil),     // 2: ai.TokenChunk
	nil,                    // 3: ai.EventRequest.SpeakerEmotionsEntry
	nil,                    // 4: ai.EventRequest.GeneralMoodEntry
}
var file_ai_proto_depIdxs = []int32{
	3, // 0: ai.EventRequest.speaker_emotions:type_name -> ai.EventRequest.SpeakerEmotionsEntry
	4, // 1: ai.EventRequest.general_mood:type_name -> ai.EventRequest.GeneralMoodEntry
	0, // 2: ai.AIBrain.Think:input_type -> ai.EventRequest
	0, // 3: ai.AIBrain.ThinkStream:input_type -> ai.EventRequest
	1, // 4: ai.AIBrain.Think:output_type -> ai.ActionResponse
	2, // 5: ai.AIBrain.ThinkStream:output_type -> ai.TokenChunk
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ai_proto_init() }
func file_ai_proto_init() {
	if File_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_proto_rawDesc), len(file_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ai_proto_goTypes,
		DependencyIndexes: file_ai_proto_depIdxs,
		MessageInfos:      file_ai_proto_msgTypes,
	}.Build()
	File_ai_proto = out.File
	file_ai_proto_goTypes = nil
	file_ai_proto_depIdxs = nil
}
