// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: ai.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AIBrainClient is the client API for AIBrain service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIBrainClient interface {
	Think(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ActionResponse, error)
}

type aIBrainClient struct {
	cc grpc.ClientConnInterface
}

func NewAIBrainClient(cc grpc.ClientConnInterface) AIBrainClient {
	return &aIBrainClient{cc}
}

func (c *aIBrainClient) Think(ctx context.Context, in *EventRequest, opts ...grpc.CallOption) (*ActionResponse, error) {
	out := new(ActionResponse)
	err := c.cc.Invoke(ctx, "/ai.AIBrain/Think", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIBrainServer is the server API for AIBrain service.
// All implementations must embed UnimplementedAIBrainServer
// for forward compatibility
type AIBrainServer interface {
	Think(context.Context, *EventRequest) (*ActionResponse, error)
	mustEmbedUnimplementedAIBrainServer()
}

// UnimplementedAIBrainServer must be embedded to have forward compatible implementations.
type UnimplementedAIBrainServer struct {
}

func (UnimplementedAIBrainServer) Think(context.Context, *EventRequest) (*ActionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Think not implemented")
}
func (UnimplementedAIBrainServer) mustEmbedUnimplementedAIBrainServer() {}

// UnsafeAIBrainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIBrainServer will
// result in compilation errors.
type UnsafeAIBrainServer interface {
	mustEmbedUnimplementedAIBrainServer()
}

func RegisterAIBrainServer(s grpc.ServiceRegistrar, srv AIBrainServer) {
	s.RegisterService(&AIBrain_ServiceDesc, srv)
}

func _AIBrain_Think_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIBrainServer).Think(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ai.AIBrain/Think",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIBrainServer).Think(ctx, req.(*EventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIBrain_ServiceDesc is the grpc.ServiceDesc for AIBrain service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIBrain_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIBrain",
	HandlerType: (*AIBrainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Think",
			Handler:    _AIBrain_Think_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ai.proto",
}
