// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/inventoryitem"
	"agentic-npc-backend/internal/db/ent/item"
	"agentic-npc-backend/internal/db/ent/player"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// InventoryItemCreate is the builder for creating a InventoryItem entity.
type InventoryItemCreate struct {
	config
	mutation *InventoryItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQuantity sets the "quantity" field.
func (_c *InventoryItemCreate) SetQuantity(v int) *InventoryItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_c *InventoryItemCreate) SetNillableQuantity(v *int) *InventoryItemCreate {
	if v != nil {
		_c.SetQuantity(*v)
	}
	return _c
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_c *InventoryItemCreate) SetPlayerID(id uuid.UUID) *InventoryItemCreate {
	_c.mutation.SetPlayerID(id)
	return _c
}

// SetPlayer sets the "player" edge to the Player entity.
func (_c *InventoryItemCreate) SetPlayer(v *Player) *InventoryItemCreate {
	return _c.SetPlayerID(v.ID)
}

// SetItemID sets the "item" edge to the Item entity by ID.
func (_c *InventoryItemCreate) SetItemID(id int) *InventoryItemCreate {
	_c.mutation.SetItemID(id)
	return _c
}

// SetItem sets the "item" edge to the Item entity.
func (_c *InventoryItemCreate) SetItem(v *Item) *InventoryItemCreate {
	return _c.SetItemID(v.ID)
}

// Mutation returns the InventoryItemMutation object of the builder.
func (_c *InventoryItemCreate) Mutation() *InventoryItemMutation {
	return _c.mutation
}

// Save creates the InventoryItem in the database.
func (_c *InventoryItemCreate) Save(ctx context.Context) (*InventoryItem, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InventoryItemCreate) SaveX(ctx context.Context) *InventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InventoryItemCreate) defaults() {
	if _, ok := _c.mutation.Quantity(); !ok {
		v := inventoryitem.DefaultQuantity
		_c.mutation.SetQuantity(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InventoryItemCreate) check() error {
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "InventoryItem.quantity"`)}
	}
	if len(_c.mutation.PlayerIDs()) == 0 {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "InventoryItem.player"`)}
	}
	if len(_c.mutation.ItemIDs()) == 0 {
		return &ValidationError{Name: "item", err: errors.New(`ent: missing required edge "InventoryItem.item"`)}
	}
	return nil
}

func (_c *InventoryItemCreate) sqlSave(ctx context.Context) (*InventoryItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InventoryItemCreate) createSpec() (*InventoryItem, *sqlgraph.CreateSpec) {
	var (
		_node = &InventoryItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(inventoryitem.Table, sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(inventoryitem.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventoryitem.PlayerTable,
			Columns: []string{inventoryitem.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.player_inventory = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   inventoryitem.ItemTable,
			Columns: []string{inventoryitem.ItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.item_inventory_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryItem.Create().
//		SetQuantity(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryItemUpsert) {
//			SetQuantity(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryItemCreate) OnConflict(opts ...sql.ConflictOption) *InventoryItemUpsertOne {
	_c.conflict = opts
	return &InventoryItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryItemCreate) OnConflictColumns(columns ...string) *InventoryItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryItemUpsertOne{
		create: _c,
	}
}

type (
	// InventoryItemUpsertOne is the builder for "upsert"-ing
	//  one InventoryItem node.
	InventoryItemUpsertOne struct {
		create *InventoryItemCreate
	}

	// InventoryItemUpsert is the "OnConflict" setter.
	InventoryItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuantity sets the "quantity" field.
func (u *InventoryItemUpsert) SetQuantity(v int) *InventoryItemUpsert {
	u.Set(inventoryitem.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *InventoryItemUpsert) UpdateQuantity() *InventoryItemUpsert {
	u.SetExcluded(inventoryitem.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *InventoryItemUpsert) AddQuantity(v int) *InventoryItemUpsert {
	u.Add(inventoryitem.FieldQuantity, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InventoryItemUpsertOne) UpdateNewValues() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *InventoryItemUpsertOne) Ignore() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryItemUpsertOne) DoNothing() *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryItemCreate.OnConflict
// documentation for more info.
func (u *InventoryItemUpsertOne) Update(set func(*InventoryItemUpsert)) *InventoryItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuantity sets the "quantity" field.
func (u *InventoryItemUpsertOne) SetQuantity(v int) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *InventoryItemUpsertOne) AddQuantity(v int) *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *InventoryItemUpsertOne) UpdateQuantity() *InventoryItemUpsertOne {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *InventoryItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *InventoryItemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *InventoryItemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// InventoryItemCreateBulk is the builder for creating many InventoryItem entities in bulk.
type InventoryItemCreateBulk struct {
	config
	err      error
	builders []*InventoryItemCreate
	conflict []sql.ConflictOption
}

// Save creates the InventoryItem entities in the database.
func (_c *InventoryItemCreateBulk) Save(ctx context.Context) ([]*InventoryItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InventoryItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InventoryItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InventoryItemCreateBulk) SaveX(ctx context.Context) []*InventoryItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InventoryItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InventoryItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.InventoryItem.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.InventoryItemUpsert) {
//			SetQuantity(v+v).
//		}).
//		Exec(ctx)
func (_c *InventoryItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *InventoryItemUpsertBulk {
	_c.conflict = opts
	return &InventoryItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *InventoryItemCreateBulk) OnConflictColumns(columns ...string) *InventoryItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &InventoryItemUpsertBulk{
		create: _c,
	}
}

// InventoryItemUpsertBulk is the builder for "upsert"-ing
// a bulk of InventoryItem nodes.
type InventoryItemUpsertBulk struct {
	create *InventoryItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *InventoryItemUpsertBulk) UpdateNewValues() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.InventoryItem.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *InventoryItemUpsertBulk) Ignore() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *InventoryItemUpsertBulk) DoNothing() *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the InventoryItemCreateBulk.OnConflict
// documentation for more info.
func (u *InventoryItemUpsertBulk) Update(set func(*InventoryItemUpsert)) *InventoryItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&InventoryItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuantity sets the "quantity" field.
func (u *InventoryItemUpsertBulk) SetQuantity(v int) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *InventoryItemUpsertBulk) AddQuantity(v int) *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *InventoryItemUpsertBulk) UpdateQuantity() *InventoryItemUpsertBulk {
	return u.Update(func(s *InventoryItemUpsert) {
		s.UpdateQuantity()
	})
}

// Exec executes the query.
func (u *InventoryItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the InventoryItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for InventoryItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *InventoryItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
