// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/inventoryitem"
	"agentic-npc-backend/internal/db/ent/item"
	"agentic-npc-backend/internal/db/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemUpdate is the builder for updating Item entities.
type ItemUpdate struct {
	config
	hooks    []Hook
	mutation *ItemMutation
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdate) Where(ps ...predicate.Item) *ItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetItemID sets the "item_id" field.
func (_u *ItemUpdate) SetItemID(v string) *ItemUpdate {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableItemID(v *string) *ItemUpdate {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ItemUpdate) SetName(v string) *ItemUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableName(v *string) *ItemUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *ItemUpdate) SetRarity(v string) *ItemUpdate {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableRarity(v *string) *ItemUpdate {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (_u *ItemUpdate) SetBaseTrustValue(v float64) *ItemUpdate {
	_u.mutation.ResetBaseTrustValue()
	_u.mutation.SetBaseTrustValue(v)
	return _u
}

// SetNillableBaseTrustValue sets the "base_trust_value" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableBaseTrustValue(v *float64) *ItemUpdate {
	if v != nil {
		_u.SetBaseTrustValue(*v)
	}
	return _u
}

// AddBaseTrustValue adds value to the "base_trust_value" field.
func (_u *ItemUpdate) AddBaseTrustValue(v float64) *ItemUpdate {
	_u.mutation.AddBaseTrustValue(v)
	return _u
}

// SetQuestItem sets the "quest_item" field.
func (_u *ItemUpdate) SetQuestItem(v bool) *ItemUpdate {
	_u.mutation.SetQuestItem(v)
	return _u
}

// SetNillableQuestItem sets the "quest_item" field if the given value is not nil.
func (_u *ItemUpdate) SetNillableQuestItem(v *bool) *ItemUpdate {
	if v != nil {
		_u.SetQuestItem(*v)
	}
	return _u
}

// AddInventoryItemIDs adds the "inventory_items" edge to the InventoryItem entity by IDs.
func (_u *ItemUpdate) AddInventoryItemIDs(ids ...int) *ItemUpdate {
	_u.mutation.AddInventoryItemIDs(ids...)
	return _u
}

// AddInventoryItems adds the "inventory_items" edges to the InventoryItem entity.
func (_u *ItemUpdate) AddInventoryItems(v ...*InventoryItem) *ItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryItemIDs(ids...)
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdate) Mutation() *ItemMutation {
	return _u.mutation
}

// ClearInventoryItems clears all "inventory_items" edges to the InventoryItem entity.
func (_u *ItemUpdate) ClearInventoryItems() *ItemUpdate {
	_u.mutation.ClearInventoryItems()
	return _u
}

// RemoveInventoryItemIDs removes the "inventory_items" edge to InventoryItem entities by IDs.
func (_u *ItemUpdate) RemoveInventoryItemIDs(ids ...int) *ItemUpdate {
	_u.mutation.RemoveInventoryItemIDs(ids...)
	return _u
}

// RemoveInventoryItems removes "inventory_items" edges to InventoryItem entities.
func (_u *ItemUpdate) RemoveInventoryItems(v ...*InventoryItem) *ItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdate) check() error {
	if v, ok := _u.mutation.ItemID(); ok {
		if err := item.ItemIDValidator(v); err != nil {
			return &ValidationError{Name: "item_id", err: fmt.Errorf(`ent: validator failed for field "Item.item_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := item.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "Item.rarity": %w`, err)}
		}
	}
	return nil
}

func (_u *ItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(item.FieldItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(item.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseTrustValue(); ok {
		_spec.SetField(item.FieldBaseTrustValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseTrustValue(); ok {
		_spec.AddField(item.FieldBaseTrustValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuestItem(); ok {
		_spec.SetField(item.FieldQuestItem, field.TypeBool, value)
	}
	if _u.mutation.InventoryItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryItemsIDs(); len(nodes) > 0 && !_u.mutation.InventoryItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ItemUpdateOne is the builder for updating a single Item entity.
type ItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ItemMutation
}

// SetItemID sets the "item_id" field.
func (_u *ItemUpdateOne) SetItemID(v string) *ItemUpdateOne {
	_u.mutation.SetItemID(v)
	return _u
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableItemID(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetItemID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ItemUpdateOne) SetName(v string) *ItemUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableName(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetRarity sets the "rarity" field.
func (_u *ItemUpdateOne) SetRarity(v string) *ItemUpdateOne {
	_u.mutation.SetRarity(v)
	return _u
}

// SetNillableRarity sets the "rarity" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableRarity(v *string) *ItemUpdateOne {
	if v != nil {
		_u.SetRarity(*v)
	}
	return _u
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (_u *ItemUpdateOne) SetBaseTrustValue(v float64) *ItemUpdateOne {
	_u.mutation.ResetBaseTrustValue()
	_u.mutation.SetBaseTrustValue(v)
	return _u
}

// SetNillableBaseTrustValue sets the "base_trust_value" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableBaseTrustValue(v *float64) *ItemUpdateOne {
	if v != nil {
		_u.SetBaseTrustValue(*v)
	}
	return _u
}

// AddBaseTrustValue adds value to the "base_trust_value" field.
func (_u *ItemUpdateOne) AddBaseTrustValue(v float64) *ItemUpdateOne {
	_u.mutation.AddBaseTrustValue(v)
	return _u
}

// SetQuestItem sets the "quest_item" field.
func (_u *ItemUpdateOne) SetQuestItem(v bool) *ItemUpdateOne {
	_u.mutation.SetQuestItem(v)
	return _u
}

// SetNillableQuestItem sets the "quest_item" field if the given value is not nil.
func (_u *ItemUpdateOne) SetNillableQuestItem(v *bool) *ItemUpdateOne {
	if v != nil {
		_u.SetQuestItem(*v)
	}
	return _u
}

// AddInventoryItemIDs adds the "inventory_items" edge to the InventoryItem entity by IDs.
func (_u *ItemUpdateOne) AddInventoryItemIDs(ids ...int) *ItemUpdateOne {
	_u.mutation.AddInventoryItemIDs(ids...)
	return _u
}

// AddInventoryItems adds the "inventory_items" edges to the InventoryItem entity.
func (_u *ItemUpdateOne) AddInventoryItems(v ...*InventoryItem) *ItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryItemIDs(ids...)
}

// Mutation returns the ItemMutation object of the builder.
func (_u *ItemUpdateOne) Mutation() *ItemMutation {
	return _u.mutation
}

// ClearInventoryItems clears all "inventory_items" edges to the InventoryItem entity.
func (_u *ItemUpdateOne) ClearInventoryItems() *ItemUpdateOne {
	_u.mutation.ClearInventoryItems()
	return _u
}

// RemoveInventoryItemIDs removes the "inventory_items" edge to InventoryItem entities by IDs.
func (_u *ItemUpdateOne) RemoveInventoryItemIDs(ids ...int) *ItemUpdateOne {
	_u.mutation.RemoveInventoryItemIDs(ids...)
	return _u
}

// RemoveInventoryItems removes "inventory_items" edges to InventoryItem entities.
func (_u *ItemUpdateOne) RemoveInventoryItems(v ...*InventoryItem) *ItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryItemIDs(ids...)
}

// Where appends a list predicates to the ItemUpdate builder.
func (_u *ItemUpdateOne) Where(ps ...predicate.Item) *ItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ItemUpdateOne) Select(field string, fields ...string) *ItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Item entity.
func (_u *ItemUpdateOne) Save(ctx context.Context) (*Item, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ItemUpdateOne) SaveX(ctx context.Context) *Item {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ItemUpdateOne) check() error {
	if v, ok := _u.mutation.ItemID(); ok {
		if err := item.ItemIDValidator(v); err != nil {
			return &ValidationError{Name: "item_id", err: fmt.Errorf(`ent: validator failed for field "Item.item_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Rarity(); ok {
		if err := item.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "Item.rarity": %w`, err)}
		}
	}
	return nil
}

func (_u *ItemUpdateOne) sqlSave(ctx context.Context) (_node *Item, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(item.Table, item.Columns, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Item.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, item.FieldID)
		for _, f := range fields {
			if !item.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != item.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ItemID(); ok {
		_spec.SetField(item.FieldItemID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rarity(); ok {
		_spec.SetField(item.FieldRarity, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseTrustValue(); ok {
		_spec.SetField(item.FieldBaseTrustValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBaseTrustValue(); ok {
		_spec.AddField(item.FieldBaseTrustValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuestItem(); ok {
		_spec.SetField(item.FieldQuestItem, field.TypeBool, value)
	}
	if _u.mutation.InventoryItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryItemsIDs(); len(nodes) > 0 && !_u.mutation.InventoryItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Item{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{item.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
