// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/inventoryitem"
	"agentic-npc-backend/internal/db/ent/item"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ItemCreate is the builder for creating a Item entity.
type ItemCreate struct {
	config
	mutation *ItemMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetItemID sets the "item_id" field.
func (_c *ItemCreate) SetItemID(v string) *ItemCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *ItemCreate) SetName(v string) *ItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetRarity sets the "rarity" field.
func (_c *ItemCreate) SetRarity(v string) *ItemCreate {
	_c.mutation.SetRarity(v)
	return _c
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (_c *ItemCreate) SetBaseTrustValue(v float64) *ItemCreate {
	_c.mutation.SetBaseTrustValue(v)
	return _c
}

// SetNillableBaseTrustValue sets the "base_trust_value" field if the given value is not nil.
func (_c *ItemCreate) SetNillableBaseTrustValue(v *float64) *ItemCreate {
	if v != nil {
		_c.SetBaseTrustValue(*v)
	}
	return _c
}

// SetQuestItem sets the "quest_item" field.
func (_c *ItemCreate) SetQuestItem(v bool) *ItemCreate {
	_c.mutation.SetQuestItem(v)
	return _c
}

// SetNillableQuestItem sets the "quest_item" field if the given value is not nil.
func (_c *ItemCreate) SetNillableQuestItem(v *bool) *ItemCreate {
	if v != nil {
		_c.SetQuestItem(*v)
	}
	return _c
}

// AddInventoryItemIDs adds the "inventory_items" edge to the InventoryItem entity by IDs.
func (_c *ItemCreate) AddInventoryItemIDs(ids ...int) *ItemCreate {
	_c.mutation.AddInventoryItemIDs(ids...)
	return _c
}

// AddInventoryItems adds the "inventory_items" edges to the InventoryItem entity.
func (_c *ItemCreate) AddInventoryItems(v ...*InventoryItem) *ItemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInventoryItemIDs(ids...)
}

// Mutation returns the ItemMutation object of the builder.
func (_c *ItemCreate) Mutation() *ItemMutation {
	return _c.mutation
}

// Save creates the Item in the database.
func (_c *ItemCreate) Save(ctx context.Context) (*Item, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ItemCreate) SaveX(ctx context.Context) *Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ItemCreate) defaults() {
	if _, ok := _c.mutation.BaseTrustValue(); !ok {
		v := item.DefaultBaseTrustValue
		_c.mutation.SetBaseTrustValue(v)
	}
	if _, ok := _c.mutation.QuestItem(); !ok {
		v := item.DefaultQuestItem
		_c.mutation.SetQuestItem(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ItemCreate) check() error {
	if _, ok := _c.mutation.ItemID(); !ok {
		return &ValidationError{Name: "item_id", err: errors.New(`ent: missing required field "Item.item_id"`)}
	}
	if v, ok := _c.mutation.ItemID(); ok {
		if err := item.ItemIDValidator(v); err != nil {
			return &ValidationError{Name: "item_id", err: fmt.Errorf(`ent: validator failed for field "Item.item_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Item.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := item.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Item.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Rarity(); !ok {
		return &ValidationError{Name: "rarity", err: errors.New(`ent: missing required field "Item.rarity"`)}
	}
	if v, ok := _c.mutation.Rarity(); ok {
		if err := item.RarityValidator(v); err != nil {
			return &ValidationError{Name: "rarity", err: fmt.Errorf(`ent: validator failed for field "Item.rarity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseTrustValue(); !ok {
		return &ValidationError{Name: "base_trust_value", err: errors.New(`ent: missing required field "Item.base_trust_value"`)}
	}
	if _, ok := _c.mutation.QuestItem(); !ok {
		return &ValidationError{Name: "quest_item", err: errors.New(`ent: missing required field "Item.quest_item"`)}
	}
	return nil
}

func (_c *ItemCreate) sqlSave(ctx context.Context) (*Item, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ItemCreate) createSpec() (*Item, *sqlgraph.CreateSpec) {
	var (
		_node = &Item{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(item.Table, sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(item.FieldItemID, field.TypeString, value)
		_node.ItemID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(item.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Rarity(); ok {
		_spec.SetField(item.FieldRarity, field.TypeString, value)
		_node.Rarity = value
	}
	if value, ok := _c.mutation.BaseTrustValue(); ok {
		_spec.SetField(item.FieldBaseTrustValue, field.TypeFloat64, value)
		_node.BaseTrustValue = value
	}
	if value, ok := _c.mutation.QuestItem(); ok {
		_spec.SetField(item.FieldQuestItem, field.TypeBool, value)
		_node.QuestItem = value
	}
	if nodes := _c.mutation.InventoryItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   item.InventoryItemsTable,
			Columns: []string{item.InventoryItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Item.Create().
//		SetItemID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemCreate) OnConflict(opts ...sql.ConflictOption) *ItemUpsertOne {
	_c.conflict = opts
	return &ItemUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemCreate) OnConflictColumns(columns ...string) *ItemUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemUpsertOne{
		create: _c,
	}
}

type (
	// ItemUpsertOne is the builder for "upsert"-ing
	//  one Item node.
	ItemUpsertOne struct {
		create *ItemCreate
	}

	// ItemUpsert is the "OnConflict" setter.
	ItemUpsert struct {
		*sql.UpdateSet
	}
)

// SetItemID sets the "item_id" field.
func (u *ItemUpsert) SetItemID(v string) *ItemUpsert {
	u.Set(item.FieldItemID, v)
	return u
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemUpsert) UpdateItemID() *ItemUpsert {
	u.SetExcluded(item.FieldItemID)
	return u
}

// SetName sets the "name" field.
func (u *ItemUpsert) SetName(v string) *ItemUpsert {
	u.Set(item.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemUpsert) UpdateName() *ItemUpsert {
	u.SetExcluded(item.FieldName)
	return u
}

// SetRarity sets the "rarity" field.
func (u *ItemUpsert) SetRarity(v string) *ItemUpsert {
	u.Set(item.FieldRarity, v)
	return u
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *ItemUpsert) UpdateRarity() *ItemUpsert {
	u.SetExcluded(item.FieldRarity)
	return u
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (u *ItemUpsert) SetBaseTrustValue(v float64) *ItemUpsert {
	u.Set(item.FieldBaseTrustValue, v)
	return u
}

// UpdateBaseTrustValue sets the "base_trust_value" field to the value that was provided on create.
func (u *ItemUpsert) UpdateBaseTrustValue() *ItemUpsert {
	u.SetExcluded(item.FieldBaseTrustValue)
	return u
}

// AddBaseTrustValue adds v to the "base_trust_value" field.
func (u *ItemUpsert) AddBaseTrustValue(v float64) *ItemUpsert {
	u.Add(item.FieldBaseTrustValue, v)
	return u
}

// SetQuestItem sets the "quest_item" field.
func (u *ItemUpsert) SetQuestItem(v bool) *ItemUpsert {
	u.Set(item.FieldQuestItem, v)
	return u
}

// UpdateQuestItem sets the "quest_item" field to the value that was provided on create.
func (u *ItemUpsert) UpdateQuestItem() *ItemUpsert {
	u.SetExcluded(item.FieldQuestItem)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ItemUpsertOne) UpdateNewValues() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ItemUpsertOne) Ignore() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemUpsertOne) DoNothing() *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemCreate.OnConflict
// documentation for more info.
func (u *ItemUpsertOne) Update(set func(*ItemUpsert)) *ItemUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemUpsertOne) SetItemID(v string) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateItemID() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateItemID()
	})
}

// SetName sets the "name" field.
func (u *ItemUpsertOne) SetName(v string) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateName() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateName()
	})
}

// SetRarity sets the "rarity" field.
func (u *ItemUpsertOne) SetRarity(v string) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateRarity() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateRarity()
	})
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (u *ItemUpsertOne) SetBaseTrustValue(v float64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetBaseTrustValue(v)
	})
}

// AddBaseTrustValue adds v to the "base_trust_value" field.
func (u *ItemUpsertOne) AddBaseTrustValue(v float64) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.AddBaseTrustValue(v)
	})
}

// UpdateBaseTrustValue sets the "base_trust_value" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateBaseTrustValue() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateBaseTrustValue()
	})
}

// SetQuestItem sets the "quest_item" field.
func (u *ItemUpsertOne) SetQuestItem(v bool) *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.SetQuestItem(v)
	})
}

// UpdateQuestItem sets the "quest_item" field to the value that was provided on create.
func (u *ItemUpsertOne) UpdateQuestItem() *ItemUpsertOne {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateQuestItem()
	})
}

// Exec executes the query.
func (u *ItemUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ItemUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ItemUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ItemCreateBulk is the builder for creating many Item entities in bulk.
type ItemCreateBulk struct {
	config
	err      error
	builders []*ItemCreate
	conflict []sql.ConflictOption
}

// Save creates the Item entities in the database.
func (_c *ItemCreateBulk) Save(ctx context.Context) ([]*Item, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Item, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ItemCreateBulk) SaveX(ctx context.Context) []*Item {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Item.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ItemUpsert) {
//			SetItemID(v+v).
//		}).
//		Exec(ctx)
func (_c *ItemCreateBulk) OnConflict(opts ...sql.ConflictOption) *ItemUpsertBulk {
	_c.conflict = opts
	return &ItemUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ItemCreateBulk) OnConflictColumns(columns ...string) *ItemUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ItemUpsertBulk{
		create: _c,
	}
}

// ItemUpsertBulk is the builder for "upsert"-ing
// a bulk of Item nodes.
type ItemUpsertBulk struct {
	create *ItemCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ItemUpsertBulk) UpdateNewValues() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Item.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ItemUpsertBulk) Ignore() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ItemUpsertBulk) DoNothing() *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ItemCreateBulk.OnConflict
// documentation for more info.
func (u *ItemUpsertBulk) Update(set func(*ItemUpsert)) *ItemUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ItemUpsert{UpdateSet: update})
	}))
	return u
}

// SetItemID sets the "item_id" field.
func (u *ItemUpsertBulk) SetItemID(v string) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetItemID(v)
	})
}

// UpdateItemID sets the "item_id" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateItemID() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateItemID()
	})
}

// SetName sets the "name" field.
func (u *ItemUpsertBulk) SetName(v string) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateName() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateName()
	})
}

// SetRarity sets the "rarity" field.
func (u *ItemUpsertBulk) SetRarity(v string) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetRarity(v)
	})
}

// UpdateRarity sets the "rarity" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateRarity() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateRarity()
	})
}

// SetBaseTrustValue sets the "base_trust_value" field.
func (u *ItemUpsertBulk) SetBaseTrustValue(v float64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetBaseTrustValue(v)
	})
}

// AddBaseTrustValue adds v to the "base_trust_value" field.
func (u *ItemUpsertBulk) AddBaseTrustValue(v float64) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.AddBaseTrustValue(v)
	})
}

// UpdateBaseTrustValue sets the "base_trust_value" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateBaseTrustValue() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateBaseTrustValue()
	})
}

// SetQuestItem sets the "quest_item" field.
func (u *ItemUpsertBulk) SetQuestItem(v bool) *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.SetQuestItem(v)
	})
}

// UpdateQuestItem sets the "quest_item" field to the value that was provided on create.
func (u *ItemUpsertBulk) UpdateQuestItem() *ItemUpsertBulk {
	return u.Update(func(s *ItemUpsert) {
		s.UpdateQuestItem()
	})
}

// Exec executes the query.
func (u *ItemUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ItemCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ItemCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ItemUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
