// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/predicate"
	"agentic-npc-backend/internal/db/ent/quest"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlayerQuestStateUpdate is the builder for updating PlayerQuestState entities.
type PlayerQuestStateUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerQuestStateMutation
}

// Where appends a list predicates to the PlayerQuestStateUpdate builder.
func (_u *PlayerQuestStateUpdate) Where(ps ...predicate.PlayerQuestState) *PlayerQuestStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuestIdentifier sets the "quest_identifier" field.
func (_u *PlayerQuestStateUpdate) SetQuestIdentifier(v string) *PlayerQuestStateUpdate {
	_u.mutation.SetQuestIdentifier(v)
	return _u
}

// SetNillableQuestIdentifier sets the "quest_identifier" field if the given value is not nil.
func (_u *PlayerQuestStateUpdate) SetNillableQuestIdentifier(v *string) *PlayerQuestStateUpdate {
	if v != nil {
		_u.SetQuestIdentifier(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *PlayerQuestStateUpdate) SetCurrentStep(v int) *PlayerQuestStateUpdate {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *PlayerQuestStateUpdate) SetNillableCurrentStep(v *int) *PlayerQuestStateUpdate {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *PlayerQuestStateUpdate) AddCurrentStep(v int) *PlayerQuestStateUpdate {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *PlayerQuestStateUpdate) SetIsCompleted(v bool) *PlayerQuestStateUpdate {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *PlayerQuestStateUpdate) SetNillableIsCompleted(v *bool) *PlayerQuestStateUpdate {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetCompletionRate sets the "completion_rate" field.
func (_u *PlayerQuestStateUpdate) SetCompletionRate(v float32) *PlayerQuestStateUpdate {
	_u.mutation.ResetCompletionRate()
	_u.mutation.SetCompletionRate(v)
	return _u
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_u *PlayerQuestStateUpdate) SetNillableCompletionRate(v *float32) *PlayerQuestStateUpdate {
	if v != nil {
		_u.SetCompletionRate(*v)
	}
	return _u
}

// AddCompletionRate adds value to the "completion_rate" field.
func (_u *PlayerQuestStateUpdate) AddCompletionRate(v float32) *PlayerQuestStateUpdate {
	_u.mutation.AddCompletionRate(v)
	return _u
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_u *PlayerQuestStateUpdate) SetPlayerID(id uuid.UUID) *PlayerQuestStateUpdate {
	_u.mutation.SetPlayerID(id)
	return _u
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *PlayerQuestStateUpdate) SetPlayer(v *Player) *PlayerQuestStateUpdate {
	return _u.SetPlayerID(v.ID)
}

// SetQuestID sets the "quest" edge to the Quest entity by ID.
func (_u *PlayerQuestStateUpdate) SetQuestID(id string) *PlayerQuestStateUpdate {
	_u.mutation.SetQuestID(id)
	return _u
}

// SetQuest sets the "quest" edge to the Quest entity.
func (_u *PlayerQuestStateUpdate) SetQuest(v *Quest) *PlayerQuestStateUpdate {
	return _u.SetQuestID(v.ID)
}

// Mutation returns the PlayerQuestStateMutation object of the builder.
func (_u *PlayerQuestStateUpdate) Mutation() *PlayerQuestStateMutation {
	return _u.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *PlayerQuestStateUpdate) ClearPlayer() *PlayerQuestStateUpdate {
	_u.mutation.ClearPlayer()
	return _u
}

// ClearQuest clears the "quest" edge to the Quest entity.
func (_u *PlayerQuestStateUpdate) ClearQuest() *PlayerQuestStateUpdate {
	_u.mutation.ClearQuest()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerQuestStateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerQuestStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerQuestStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerQuestStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerQuestStateUpdate) check() error {
	if v, ok := _u.mutation.QuestIdentifier(); ok {
		if err := playerqueststate.QuestIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "quest_identifier", err: fmt.Errorf(`ent: validator failed for field "PlayerQuestState.quest_identifier": %w`, err)}
		}
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerQuestState.player"`)
	}
	if _u.mutation.QuestCleared() && len(_u.mutation.QuestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerQuestState.quest"`)
	}
	return nil
}

func (_u *PlayerQuestStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerqueststate.Table, playerqueststate.Columns, sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.QuestIdentifier(); ok {
		_spec.SetField(playerqueststate.FieldQuestIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(playerqueststate.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(playerqueststate.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(playerqueststate.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletionRate(); ok {
		_spec.SetField(playerqueststate.FieldCompletionRate, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedCompletionRate(); ok {
		_spec.AddField(playerqueststate.FieldCompletionRate, field.TypeFloat32, value)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.PlayerTable,
			Columns: []string{playerqueststate.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.PlayerTable,
			Columns: []string{playerqueststate.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.QuestTable,
			Columns: []string{playerqueststate.QuestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.QuestTable,
			Columns: []string{playerqueststate.QuestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerqueststate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerQuestStateUpdateOne is the builder for updating a single PlayerQuestState entity.
type PlayerQuestStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerQuestStateMutation
}

// SetQuestIdentifier sets the "quest_identifier" field.
func (_u *PlayerQuestStateUpdateOne) SetQuestIdentifier(v string) *PlayerQuestStateUpdateOne {
	_u.mutation.SetQuestIdentifier(v)
	return _u
}

// SetNillableQuestIdentifier sets the "quest_identifier" field if the given value is not nil.
func (_u *PlayerQuestStateUpdateOne) SetNillableQuestIdentifier(v *string) *PlayerQuestStateUpdateOne {
	if v != nil {
		_u.SetQuestIdentifier(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *PlayerQuestStateUpdateOne) SetCurrentStep(v int) *PlayerQuestStateUpdateOne {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *PlayerQuestStateUpdateOne) SetNillableCurrentStep(v *int) *PlayerQuestStateUpdateOne {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *PlayerQuestStateUpdateOne) AddCurrentStep(v int) *PlayerQuestStateUpdateOne {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetIsCompleted sets the "is_completed" field.
func (_u *PlayerQuestStateUpdateOne) SetIsCompleted(v bool) *PlayerQuestStateUpdateOne {
	_u.mutation.SetIsCompleted(v)
	return _u
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_u *PlayerQuestStateUpdateOne) SetNillableIsCompleted(v *bool) *PlayerQuestStateUpdateOne {
	if v != nil {
		_u.SetIsCompleted(*v)
	}
	return _u
}

// SetCompletionRate sets the "completion_rate" field.
func (_u *PlayerQuestStateUpdateOne) SetCompletionRate(v float32) *PlayerQuestStateUpdateOne {
	_u.mutation.ResetCompletionRate()
	_u.mutation.SetCompletionRate(v)
	return _u
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_u *PlayerQuestStateUpdateOne) SetNillableCompletionRate(v *float32) *PlayerQuestStateUpdateOne {
	if v != nil {
		_u.SetCompletionRate(*v)
	}
	return _u
}

// AddCompletionRate adds value to the "completion_rate" field.
func (_u *PlayerQuestStateUpdateOne) AddCompletionRate(v float32) *PlayerQuestStateUpdateOne {
	_u.mutation.AddCompletionRate(v)
	return _u
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_u *PlayerQuestStateUpdateOne) SetPlayerID(id uuid.UUID) *PlayerQuestStateUpdateOne {
	_u.mutation.SetPlayerID(id)
	return _u
}

// SetPlayer sets the "player" edge to the Player entity.
func (_u *PlayerQuestStateUpdateOne) SetPlayer(v *Player) *PlayerQuestStateUpdateOne {
	return _u.SetPlayerID(v.ID)
}

// SetQuestID sets the "quest" edge to the Quest entity by ID.
func (_u *PlayerQuestStateUpdateOne) SetQuestID(id string) *PlayerQuestStateUpdateOne {
	_u.mutation.SetQuestID(id)
	return _u
}

// SetQuest sets the "quest" edge to the Quest entity.
func (_u *PlayerQuestStateUpdateOne) SetQuest(v *Quest) *PlayerQuestStateUpdateOne {
	return _u.SetQuestID(v.ID)
}

// Mutation returns the PlayerQuestStateMutation object of the builder.
func (_u *PlayerQuestStateUpdateOne) Mutation() *PlayerQuestStateMutation {
	return _u.mutation
}

// ClearPlayer clears the "player" edge to the Player entity.
func (_u *PlayerQuestStateUpdateOne) ClearPlayer() *PlayerQuestStateUpdateOne {
	_u.mutation.ClearPlayer()
	return _u
}

// ClearQuest clears the "quest" edge to the Quest entity.
func (_u *PlayerQuestStateUpdateOne) ClearQuest() *PlayerQuestStateUpdateOne {
	_u.mutation.ClearQuest()
	return _u
}

// Where appends a list predicates to the PlayerQuestStateUpdate builder.
func (_u *PlayerQuestStateUpdateOne) Where(ps ...predicate.PlayerQuestState) *PlayerQuestStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerQuestStateUpdateOne) Select(field string, fields ...string) *PlayerQuestStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PlayerQuestState entity.
func (_u *PlayerQuestStateUpdateOne) Save(ctx context.Context) (*PlayerQuestState, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerQuestStateUpdateOne) SaveX(ctx context.Context) *PlayerQuestState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerQuestStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerQuestStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerQuestStateUpdateOne) check() error {
	if v, ok := _u.mutation.QuestIdentifier(); ok {
		if err := playerqueststate.QuestIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "quest_identifier", err: fmt.Errorf(`ent: validator failed for field "PlayerQuestState.quest_identifier": %w`, err)}
		}
	}
	if _u.mutation.PlayerCleared() && len(_u.mutation.PlayerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerQuestState.player"`)
	}
	if _u.mutation.QuestCleared() && len(_u.mutation.QuestIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PlayerQuestState.quest"`)
	}
	return nil
}

func (_u *PlayerQuestStateUpdateOne) sqlSave(ctx context.Context) (_node *PlayerQuestState, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(playerqueststate.Table, playerqueststate.Columns, sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PlayerQuestState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playerqueststate.FieldID)
		for _, f := range fields {
			if !playerqueststate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != playerqueststate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.QuestIdentifier(); ok {
		_spec.SetField(playerqueststate.FieldQuestIdentifier, field.TypeString, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(playerqueststate.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(playerqueststate.FieldCurrentStep, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCompleted(); ok {
		_spec.SetField(playerqueststate.FieldIsCompleted, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CompletionRate(); ok {
		_spec.SetField(playerqueststate.FieldCompletionRate, field.TypeFloat32, value)
	}
	if value, ok := _u.mutation.AddedCompletionRate(); ok {
		_spec.AddField(playerqueststate.FieldCompletionRate, field.TypeFloat32, value)
	}
	if _u.mutation.PlayerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.PlayerTable,
			Columns: []string{playerqueststate.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.PlayerTable,
			Columns: []string{playerqueststate.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.QuestCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.QuestTable,
			Columns: []string{playerqueststate.QuestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.QuestTable,
			Columns: []string{playerqueststate.QuestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PlayerQuestState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{playerqueststate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
