// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/npc"
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playernpcrelationship"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PlayerNPCRelationship is the model entity for the PlayerNPCRelationship schema.
type PlayerNPCRelationship struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// The trust level between 0.0 and 1.0
	TrustLevel float64 `json:"trust_level,omitempty"`
	// The number of gifts this player has given this NPC, for diminishing returns.
	GiftCount int `json:"gift_count,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerNPCRelationshipQuery when eager-loading is set.
	Edges                    PlayerNPCRelationshipEdges `json:"edges"`
	npc_player_relationships *uuid.UUID
	player_npc_relationships *uuid.UUID
	selectValues             sql.SelectValues
}

// PlayerNPCRelationshipEdges holds the relations/edges for other nodes in the graph.
type PlayerNPCRelationshipEdges struct {
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty"`
	// Npc holds the value of the npc edge.
	Npc *NPC `json:"npc,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerNPCRelationshipEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// NpcOrErr returns the Npc value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerNPCRelationshipEdges) NpcOrErr() (*NPC, error) {
	if e.Npc != nil {
		return e.Npc, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: npc.Label}
	}
	return nil, &NotLoadedError{edge: "npc"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerNPCRelationship) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playernpcrelationship.FieldTrustLevel:
			values[i] = new(sql.NullFloat64)
		case playernpcrelationship.FieldID, playernpcrelationship.FieldGiftCount:
			values[i] = new(sql.NullInt64)
		case playernpcrelationship.ForeignKeys[0]: // npc_player_relationships
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case playernpcrelationship.ForeignKeys[1]: // player_npc_relationships
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerNPCRelationship fields.
func (_m *PlayerNPCRelationship) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playernpcrelationship.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case playernpcrelationship.FieldTrustLevel:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field trust_level", values[i])
			} else if value.Valid {
				_m.TrustLevel = value.Float64
			}
		case playernpcrelationship.FieldGiftCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field gift_count", values[i])
			} else if value.Valid {
				_m.GiftCount = int(value.Int64)
			}
		case playernpcrelationship.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field npc_player_relationships", values[i])
			} else if value.Valid {
				_m.npc_player_relationships = new(uuid.UUID)
				*_m.npc_player_relationships = *value.S.(*uuid.UUID)
			}
		case playernpcrelationship.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field player_npc_relationships", values[i])
			} else if value.Valid {
				_m.player_npc_relationships = new(uuid.UUID)
				*_m.player_npc_relationships = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerNPCRelationship.
// This includes values selected through modifiers, order, etc.
func (_m *PlayerNPCRelationship) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlayer queries the "player" edge of the PlayerNPCRelationship entity.
func (_m *PlayerNPCRelationship) QueryPlayer() *PlayerQuery {
	return NewPlayerNPCRelationshipClient(_m.config).QueryPlayer(_m)
}

// QueryNpc queries the "npc" edge of the PlayerNPCRelationship entity.
func (_m *PlayerNPCRelationship) QueryNpc() *NPCQuery {
	return NewPlayerNPCRelationshipClient(_m.config).QueryNpc(_m)
}

// Update returns a builder for updating this PlayerNPCRelationship.
// Note that you need to call PlayerNPCRelationship.Unwrap() before calling this method if this PlayerNPCRelationship
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlayerNPCRelationship) Update() *PlayerNPCRelationshipUpdateOne {
	return NewPlayerNPCRelationshipClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlayerNPCRelationship entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlayerNPCRelationship) Unwrap() *PlayerNPCRelationship {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerNPCRelationship is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlayerNPCRelationship) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerNPCRelationship(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("trust_level=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrustLevel))
	builder.WriteString(", ")
	builder.WriteString("gift_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.GiftCount))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerNPCRelationships is a parsable slice of PlayerNPCRelationship.
type PlayerNPCRelationships []*PlayerNPCRelationship
