// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/npc"
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playernpcrelationship"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlayerNPCRelationshipCreate is the builder for creating a PlayerNPCRelationship entity.
type PlayerNPCRelationshipCreate struct {
	config
	mutation *PlayerNPCRelationshipMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTrustLevel sets the "trust_level" field.
func (_c *PlayerNPCRelationshipCreate) SetTrustLevel(v float64) *PlayerNPCRelationshipCreate {
	_c.mutation.SetTrustLevel(v)
	return _c
}

// SetNillableTrustLevel sets the "trust_level" field if the given value is not nil.
func (_c *PlayerNPCRelationshipCreate) SetNillableTrustLevel(v *float64) *PlayerNPCRelationshipCreate {
	if v != nil {
		_c.SetTrustLevel(*v)
	}
	return _c
}

// SetGiftCount sets the "gift_count" field.
func (_c *PlayerNPCRelationshipCreate) SetGiftCount(v int) *PlayerNPCRelationshipCreate {
	_c.mutation.SetGiftCount(v)
	return _c
}

// SetNillableGiftCount sets the "gift_count" field if the given value is not nil.
func (_c *PlayerNPCRelationshipCreate) SetNillableGiftCount(v *int) *PlayerNPCRelationshipCreate {
	if v != nil {
		_c.SetGiftCount(*v)
	}
	return _c
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_c *PlayerNPCRelationshipCreate) SetPlayerID(id uuid.UUID) *PlayerNPCRelationshipCreate {
	_c.mutation.SetPlayerID(id)
	return _c
}

// SetPlayer sets the "player" edge to the Player entity.
func (_c *PlayerNPCRelationshipCreate) SetPlayer(v *Player) *PlayerNPCRelationshipCreate {
	return _c.SetPlayerID(v.ID)
}

// SetNpcID sets the "npc" edge to the NPC entity by ID.
func (_c *PlayerNPCRelationshipCreate) SetNpcID(id uuid.UUID) *PlayerNPCRelationshipCreate {
	_c.mutation.SetNpcID(id)
	return _c
}

// SetNpc sets the "npc" edge to the NPC entity.
func (_c *PlayerNPCRelationshipCreate) SetNpc(v *NPC) *PlayerNPCRelationshipCreate {
	return _c.SetNpcID(v.ID)
}

// Mutation returns the PlayerNPCRelationshipMutation object of the builder.
func (_c *PlayerNPCRelationshipCreate) Mutation() *PlayerNPCRelationshipMutation {
	return _c.mutation
}

// Save creates the PlayerNPCRelationship in the database.
func (_c *PlayerNPCRelationshipCreate) Save(ctx context.Context) (*PlayerNPCRelationship, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerNPCRelationshipCreate) SaveX(ctx context.Context) *PlayerNPCRelationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerNPCRelationshipCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerNPCRelationshipCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerNPCRelationshipCreate) defaults() {
	if _, ok := _c.mutation.TrustLevel(); !ok {
		v := playernpcrelationship.DefaultTrustLevel
		_c.mutation.SetTrustLevel(v)
	}
	if _, ok := _c.mutation.GiftCount(); !ok {
		v := playernpcrelationship.DefaultGiftCount
		_c.mutation.SetGiftCount(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerNPCRelationshipCreate) check() error {
	if _, ok := _c.mutation.TrustLevel(); !ok {
		return &ValidationError{Name: "trust_level", err: errors.New(`ent: missing required field "PlayerNPCRelationship.trust_level"`)}
	}
	if _, ok := _c.mutation.GiftCount(); !ok {
		return &ValidationError{Name: "gift_count", err: errors.New(`ent: missing required field "PlayerNPCRelationship.gift_count"`)}
	}
	if len(_c.mutation.PlayerIDs()) == 0 {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "PlayerNPCRelationship.player"`)}
	}
	if len(_c.mutation.NpcIDs()) == 0 {
		return &ValidationError{Name: "npc", err: errors.New(`ent: missing required edge "PlayerNPCRelationship.npc"`)}
	}
	return nil
}

func (_c *PlayerNPCRelationshipCreate) sqlSave(ctx context.Context) (*PlayerNPCRelationship, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerNPCRelationshipCreate) createSpec() (*PlayerNPCRelationship, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayerNPCRelationship{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playernpcrelationship.Table, sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.TrustLevel(); ok {
		_spec.SetField(playernpcrelationship.FieldTrustLevel, field.TypeFloat64, value)
		_node.TrustLevel = value
	}
	if value, ok := _c.mutation.GiftCount(); ok {
		_spec.SetField(playernpcrelationship.FieldGiftCount, field.TypeInt, value)
		_node.GiftCount = value
	}
	if nodes := _c.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playernpcrelationship.PlayerTable,
			Columns: []string{playernpcrelationship.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.player_npc_relationships = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NpcIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playernpcrelationship.NpcTable,
			Columns: []string{playernpcrelationship.NpcColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(npc.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.npc_player_relationships = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlayerNPCRelationship.Create().
//		SetTrustLevel(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerNPCRelationshipUpsert) {
//			SetTrustLevel(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerNPCRelationshipCreate) OnConflict(opts ...sql.ConflictOption) *PlayerNPCRelationshipUpsertOne {
	_c.conflict = opts
	return &PlayerNPCRelationshipUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerNPCRelationshipCreate) OnConflictColumns(columns ...string) *PlayerNPCRelationshipUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerNPCRelationshipUpsertOne{
		create: _c,
	}
}

type (
	// PlayerNPCRelationshipUpsertOne is the builder for "upsert"-ing
	//  one PlayerNPCRelationship node.
	PlayerNPCRelationshipUpsertOne struct {
		create *PlayerNPCRelationshipCreate
	}

	// PlayerNPCRelationshipUpsert is the "OnConflict" setter.
	PlayerNPCRelationshipUpsert struct {
		*sql.UpdateSet
	}
)

// SetTrustLevel sets the "trust_level" field.
func (u *PlayerNPCRelationshipUpsert) SetTrustLevel(v float64) *PlayerNPCRelationshipUpsert {
	u.Set(playernpcrelationship.FieldTrustLevel, v)
	return u
}

// UpdateTrustLevel sets the "trust_level" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsert) UpdateTrustLevel() *PlayerNPCRelationshipUpsert {
	u.SetExcluded(playernpcrelationship.FieldTrustLevel)
	return u
}

// AddTrustLevel adds v to the "trust_level" field.
func (u *PlayerNPCRelationshipUpsert) AddTrustLevel(v float64) *PlayerNPCRelationshipUpsert {
	u.Add(playernpcrelationship.FieldTrustLevel, v)
	return u
}

// SetGiftCount sets the "gift_count" field.
func (u *PlayerNPCRelationshipUpsert) SetGiftCount(v int) *PlayerNPCRelationshipUpsert {
	u.Set(playernpcrelationship.FieldGiftCount, v)
	return u
}

// UpdateGiftCount sets the "gift_count" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsert) UpdateGiftCount() *PlayerNPCRelationshipUpsert {
	u.SetExcluded(playernpcrelationship.FieldGiftCount)
	return u
}

// AddGiftCount adds v to the "gift_count" field.
func (u *PlayerNPCRelationshipUpsert) AddGiftCount(v int) *PlayerNPCRelationshipUpsert {
	u.Add(playernpcrelationship.FieldGiftCount, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlayerNPCRelationshipUpsertOne) UpdateNewValues() *PlayerNPCRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlayerNPCRelationshipUpsertOne) Ignore() *PlayerNPCRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerNPCRelationshipUpsertOne) DoNothing() *PlayerNPCRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerNPCRelationshipCreate.OnConflict
// documentation for more info.
func (u *PlayerNPCRelationshipUpsertOne) Update(set func(*PlayerNPCRelationshipUpsert)) *PlayerNPCRelationshipUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerNPCRelationshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrustLevel sets the "trust_level" field.
func (u *PlayerNPCRelationshipUpsertOne) SetTrustLevel(v float64) *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.SetTrustLevel(v)
	})
}

// AddTrustLevel adds v to the "trust_level" field.
func (u *PlayerNPCRelationshipUpsertOne) AddTrustLevel(v float64) *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.AddTrustLevel(v)
	})
}

// UpdateTrustLevel sets the "trust_level" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsertOne) UpdateTrustLevel() *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.UpdateTrustLevel()
	})
}

// SetGiftCount sets the "gift_count" field.
func (u *PlayerNPCRelationshipUpsertOne) SetGiftCount(v int) *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.SetGiftCount(v)
	})
}

// AddGiftCount adds v to the "gift_count" field.
func (u *PlayerNPCRelationshipUpsertOne) AddGiftCount(v int) *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.AddGiftCount(v)
	})
}

// UpdateGiftCount sets the "gift_count" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsertOne) UpdateGiftCount() *PlayerNPCRelationshipUpsertOne {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.UpdateGiftCount()
	})
}

// Exec executes the query.
func (u *PlayerNPCRelationshipUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerNPCRelationshipCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerNPCRelationshipUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlayerNPCRelationshipUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlayerNPCRelationshipUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlayerNPCRelationshipCreateBulk is the builder for creating many PlayerNPCRelationship entities in bulk.
type PlayerNPCRelationshipCreateBulk struct {
	config
	err      error
	builders []*PlayerNPCRelationshipCreate
	conflict []sql.ConflictOption
}

// Save creates the PlayerNPCRelationship entities in the database.
func (_c *PlayerNPCRelationshipCreateBulk) Save(ctx context.Context) ([]*PlayerNPCRelationship, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlayerNPCRelationship, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerNPCRelationshipMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerNPCRelationshipCreateBulk) SaveX(ctx context.Context) []*PlayerNPCRelationship {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerNPCRelationshipCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerNPCRelationshipCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlayerNPCRelationship.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerNPCRelationshipUpsert) {
//			SetTrustLevel(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerNPCRelationshipCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlayerNPCRelationshipUpsertBulk {
	_c.conflict = opts
	return &PlayerNPCRelationshipUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerNPCRelationshipCreateBulk) OnConflictColumns(columns ...string) *PlayerNPCRelationshipUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerNPCRelationshipUpsertBulk{
		create: _c,
	}
}

// PlayerNPCRelationshipUpsertBulk is the builder for "upsert"-ing
// a bulk of PlayerNPCRelationship nodes.
type PlayerNPCRelationshipUpsertBulk struct {
	create *PlayerNPCRelationshipCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlayerNPCRelationshipUpsertBulk) UpdateNewValues() *PlayerNPCRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlayerNPCRelationship.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlayerNPCRelationshipUpsertBulk) Ignore() *PlayerNPCRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerNPCRelationshipUpsertBulk) DoNothing() *PlayerNPCRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerNPCRelationshipCreateBulk.OnConflict
// documentation for more info.
func (u *PlayerNPCRelationshipUpsertBulk) Update(set func(*PlayerNPCRelationshipUpsert)) *PlayerNPCRelationshipUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerNPCRelationshipUpsert{UpdateSet: update})
	}))
	return u
}

// SetTrustLevel sets the "trust_level" field.
func (u *PlayerNPCRelationshipUpsertBulk) SetTrustLevel(v float64) *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.SetTrustLevel(v)
	})
}

// AddTrustLevel adds v to the "trust_level" field.
func (u *PlayerNPCRelationshipUpsertBulk) AddTrustLevel(v float64) *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.AddTrustLevel(v)
	})
}

// UpdateTrustLevel sets the "trust_level" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsertBulk) UpdateTrustLevel() *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.UpdateTrustLevel()
	})
}

// SetGiftCount sets the "gift_count" field.
func (u *PlayerNPCRelationshipUpsertBulk) SetGiftCount(v int) *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.SetGiftCount(v)
	})
}

// AddGiftCount adds v to the "gift_count" field.
func (u *PlayerNPCRelationshipUpsertBulk) AddGiftCount(v int) *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.AddGiftCount(v)
	})
}

// UpdateGiftCount sets the "gift_count" field to the value that was provided on create.
func (u *PlayerNPCRelationshipUpsertBulk) UpdateGiftCount() *PlayerNPCRelationshipUpsertBulk {
	return u.Update(func(s *PlayerNPCRelationshipUpsert) {
		s.UpdateGiftCount()
	})
}

// Exec executes the query.
func (u *PlayerNPCRelationshipUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlayerNPCRelationshipCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerNPCRelationshipCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerNPCRelationshipUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
