// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/inventoryitem"
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playernpcrelationship"
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlayerCreate is the builder for creating a Player entity.
type PlayerCreate struct {
	config
	mutation *PlayerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPlayerID sets the "player_id" field.
func (_c *PlayerCreate) SetPlayerID(v string) *PlayerCreate {
	_c.mutation.SetPlayerID(v)
	return _c
}

// SetPlayerName sets the "player_name" field.
func (_c *PlayerCreate) SetPlayerName(v string) *PlayerCreate {
	_c.mutation.SetPlayerName(v)
	return _c
}

// SetNillablePlayerName sets the "player_name" field if the given value is not nil.
func (_c *PlayerCreate) SetNillablePlayerName(v *string) *PlayerCreate {
	if v != nil {
		_c.SetPlayerName(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *PlayerCreate) SetPassword(v string) *PlayerCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetID sets the "id" field.
func (_c *PlayerCreate) SetID(v uuid.UUID) *PlayerCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PlayerCreate) SetNillableID(v *uuid.UUID) *PlayerCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddQuestStateIDs adds the "quest_states" edge to the PlayerQuestState entity by IDs.
func (_c *PlayerCreate) AddQuestStateIDs(ids ...int) *PlayerCreate {
	_c.mutation.AddQuestStateIDs(ids...)
	return _c
}

// AddQuestStates adds the "quest_states" edges to the PlayerQuestState entity.
func (_c *PlayerCreate) AddQuestStates(v ...*PlayerQuestState) *PlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddQuestStateIDs(ids...)
}

// AddInventoryIDs adds the "inventory" edge to the InventoryItem entity by IDs.
func (_c *PlayerCreate) AddInventoryIDs(ids ...int) *PlayerCreate {
	_c.mutation.AddInventoryIDs(ids...)
	return _c
}

// AddInventory adds the "inventory" edges to the InventoryItem entity.
func (_c *PlayerCreate) AddInventory(v ...*InventoryItem) *PlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddInventoryIDs(ids...)
}

// AddNpcRelationshipIDs adds the "npc_relationships" edge to the PlayerNPCRelationship entity by IDs.
func (_c *PlayerCreate) AddNpcRelationshipIDs(ids ...int) *PlayerCreate {
	_c.mutation.AddNpcRelationshipIDs(ids...)
	return _c
}

// AddNpcRelationships adds the "npc_relationships" edges to the PlayerNPCRelationship entity.
func (_c *PlayerCreate) AddNpcRelationships(v ...*PlayerNPCRelationship) *PlayerCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddNpcRelationshipIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_c *PlayerCreate) Mutation() *PlayerMutation {
	return _c.mutation
}

// Save creates the Player in the database.
func (_c *PlayerCreate) Save(ctx context.Context) (*Player, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerCreate) SaveX(ctx context.Context) *Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerCreate) defaults() {
	if _, ok := _c.mutation.PlayerName(); !ok {
		v := player.DefaultPlayerName
		_c.mutation.SetPlayerName(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := player.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerCreate) check() error {
	if _, ok := _c.mutation.PlayerID(); !ok {
		return &ValidationError{Name: "player_id", err: errors.New(`ent: missing required field "Player.player_id"`)}
	}
	if v, ok := _c.mutation.PlayerID(); ok {
		if err := player.PlayerIDValidator(v); err != nil {
			return &ValidationError{Name: "player_id", err: fmt.Errorf(`ent: validator failed for field "Player.player_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PlayerName(); !ok {
		return &ValidationError{Name: "player_name", err: errors.New(`ent: missing required field "Player.player_name"`)}
	}
	if _, ok := _c.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "Player.password"`)}
	}
	if v, ok := _c.mutation.Password(); ok {
		if err := player.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Player.password": %w`, err)}
		}
	}
	return nil
}

func (_c *PlayerCreate) sqlSave(ctx context.Context) (*Player, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerCreate) createSpec() (*Player, *sqlgraph.CreateSpec) {
	var (
		_node = &Player{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(player.Table, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeString, value)
		_node.PlayerID = value
	}
	if value, ok := _c.mutation.PlayerName(); ok {
		_spec.SetField(player.FieldPlayerName, field.TypeString, value)
		_node.PlayerName = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(player.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if nodes := _c.mutation.QuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.NpcRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Player.Create().
//		SetPlayerID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerUpsert) {
//			SetPlayerID(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerCreate) OnConflict(opts ...sql.ConflictOption) *PlayerUpsertOne {
	_c.conflict = opts
	return &PlayerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Player.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerCreate) OnConflictColumns(columns ...string) *PlayerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerUpsertOne{
		create: _c,
	}
}

type (
	// PlayerUpsertOne is the builder for "upsert"-ing
	//  one Player node.
	PlayerUpsertOne struct {
		create *PlayerCreate
	}

	// PlayerUpsert is the "OnConflict" setter.
	PlayerUpsert struct {
		*sql.UpdateSet
	}
)

// SetPlayerID sets the "player_id" field.
func (u *PlayerUpsert) SetPlayerID(v string) *PlayerUpsert {
	u.Set(player.FieldPlayerID, v)
	return u
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *PlayerUpsert) UpdatePlayerID() *PlayerUpsert {
	u.SetExcluded(player.FieldPlayerID)
	return u
}

// SetPlayerName sets the "player_name" field.
func (u *PlayerUpsert) SetPlayerName(v string) *PlayerUpsert {
	u.Set(player.FieldPlayerName, v)
	return u
}

// UpdatePlayerName sets the "player_name" field to the value that was provided on create.
func (u *PlayerUpsert) UpdatePlayerName() *PlayerUpsert {
	u.SetExcluded(player.FieldPlayerName)
	return u
}

// SetPassword sets the "password" field.
func (u *PlayerUpsert) SetPassword(v string) *PlayerUpsert {
	u.Set(player.FieldPassword, v)
	return u
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *PlayerUpsert) UpdatePassword() *PlayerUpsert {
	u.SetExcluded(player.FieldPassword)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Player.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(player.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlayerUpsertOne) UpdateNewValues() *PlayerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(player.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Player.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlayerUpsertOne) Ignore() *PlayerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerUpsertOne) DoNothing() *PlayerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerCreate.OnConflict
// documentation for more info.
func (u *PlayerUpsertOne) Update(set func(*PlayerUpsert)) *PlayerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlayerID sets the "player_id" field.
func (u *PlayerUpsertOne) SetPlayerID(v string) *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *PlayerUpsertOne) UpdatePlayerID() *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePlayerID()
	})
}

// SetPlayerName sets the "player_name" field.
func (u *PlayerUpsertOne) SetPlayerName(v string) *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPlayerName(v)
	})
}

// UpdatePlayerName sets the "player_name" field to the value that was provided on create.
func (u *PlayerUpsertOne) UpdatePlayerName() *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePlayerName()
	})
}

// SetPassword sets the "password" field.
func (u *PlayerUpsertOne) SetPassword(v string) *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *PlayerUpsertOne) UpdatePassword() *PlayerUpsertOne {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePassword()
	})
}

// Exec executes the query.
func (u *PlayerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlayerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PlayerUpsertOne.ID is not supported by MySQL driver. Use PlayerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlayerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlayerCreateBulk is the builder for creating many Player entities in bulk.
type PlayerCreateBulk struct {
	config
	err      error
	builders []*PlayerCreate
	conflict []sql.ConflictOption
}

// Save creates the Player entities in the database.
func (_c *PlayerCreateBulk) Save(ctx context.Context) ([]*Player, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Player, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerCreateBulk) SaveX(ctx context.Context) []*Player {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Player.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerUpsert) {
//			SetPlayerID(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlayerUpsertBulk {
	_c.conflict = opts
	return &PlayerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Player.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerCreateBulk) OnConflictColumns(columns ...string) *PlayerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerUpsertBulk{
		create: _c,
	}
}

// PlayerUpsertBulk is the builder for "upsert"-ing
// a bulk of Player nodes.
type PlayerUpsertBulk struct {
	create *PlayerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Player.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(player.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *PlayerUpsertBulk) UpdateNewValues() *PlayerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(player.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Player.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlayerUpsertBulk) Ignore() *PlayerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerUpsertBulk) DoNothing() *PlayerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerCreateBulk.OnConflict
// documentation for more info.
func (u *PlayerUpsertBulk) Update(set func(*PlayerUpsert)) *PlayerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerUpsert{UpdateSet: update})
	}))
	return u
}

// SetPlayerID sets the "player_id" field.
func (u *PlayerUpsertBulk) SetPlayerID(v string) *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPlayerID(v)
	})
}

// UpdatePlayerID sets the "player_id" field to the value that was provided on create.
func (u *PlayerUpsertBulk) UpdatePlayerID() *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePlayerID()
	})
}

// SetPlayerName sets the "player_name" field.
func (u *PlayerUpsertBulk) SetPlayerName(v string) *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPlayerName(v)
	})
}

// UpdatePlayerName sets the "player_name" field to the value that was provided on create.
func (u *PlayerUpsertBulk) UpdatePlayerName() *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePlayerName()
	})
}

// SetPassword sets the "password" field.
func (u *PlayerUpsertBulk) SetPassword(v string) *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.SetPassword(v)
	})
}

// UpdatePassword sets the "password" field to the value that was provided on create.
func (u *PlayerUpsertBulk) UpdatePassword() *PlayerUpsertBulk {
	return u.Update(func(s *PlayerUpsert) {
		s.UpdatePassword()
	})
}

// Exec executes the query.
func (u *PlayerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlayerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
