// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/inventoryitem"
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playernpcrelationship"
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PlayerUpdate is the builder for updating Player entities.
type PlayerUpdate struct {
	config
	hooks    []Hook
	mutation *PlayerMutation
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdate) Where(ps ...predicate.Player) *PlayerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPlayerID sets the "player_id" field.
func (_u *PlayerUpdate) SetPlayerID(v string) *PlayerUpdate {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePlayerID(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetPlayerName sets the "player_name" field.
func (_u *PlayerUpdate) SetPlayerName(v string) *PlayerUpdate {
	_u.mutation.SetPlayerName(v)
	return _u
}

// SetNillablePlayerName sets the "player_name" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePlayerName(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetPlayerName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *PlayerUpdate) SetPassword(v string) *PlayerUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *PlayerUpdate) SetNillablePassword(v *string) *PlayerUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// AddQuestStateIDs adds the "quest_states" edge to the PlayerQuestState entity by IDs.
func (_u *PlayerUpdate) AddQuestStateIDs(ids ...int) *PlayerUpdate {
	_u.mutation.AddQuestStateIDs(ids...)
	return _u
}

// AddQuestStates adds the "quest_states" edges to the PlayerQuestState entity.
func (_u *PlayerUpdate) AddQuestStates(v ...*PlayerQuestState) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestStateIDs(ids...)
}

// AddInventoryIDs adds the "inventory" edge to the InventoryItem entity by IDs.
func (_u *PlayerUpdate) AddInventoryIDs(ids ...int) *PlayerUpdate {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventory adds the "inventory" edges to the InventoryItem entity.
func (_u *PlayerUpdate) AddInventory(v ...*InventoryItem) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// AddNpcRelationshipIDs adds the "npc_relationships" edge to the PlayerNPCRelationship entity by IDs.
func (_u *PlayerUpdate) AddNpcRelationshipIDs(ids ...int) *PlayerUpdate {
	_u.mutation.AddNpcRelationshipIDs(ids...)
	return _u
}

// AddNpcRelationships adds the "npc_relationships" edges to the PlayerNPCRelationship entity.
func (_u *PlayerUpdate) AddNpcRelationships(v ...*PlayerNPCRelationship) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNpcRelationshipIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdate) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearQuestStates clears all "quest_states" edges to the PlayerQuestState entity.
func (_u *PlayerUpdate) ClearQuestStates() *PlayerUpdate {
	_u.mutation.ClearQuestStates()
	return _u
}

// RemoveQuestStateIDs removes the "quest_states" edge to PlayerQuestState entities by IDs.
func (_u *PlayerUpdate) RemoveQuestStateIDs(ids ...int) *PlayerUpdate {
	_u.mutation.RemoveQuestStateIDs(ids...)
	return _u
}

// RemoveQuestStates removes "quest_states" edges to PlayerQuestState entities.
func (_u *PlayerUpdate) RemoveQuestStates(v ...*PlayerQuestState) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestStateIDs(ids...)
}

// ClearInventory clears all "inventory" edges to the InventoryItem entity.
func (_u *PlayerUpdate) ClearInventory() *PlayerUpdate {
	_u.mutation.ClearInventory()
	return _u
}

// RemoveInventoryIDs removes the "inventory" edge to InventoryItem entities by IDs.
func (_u *PlayerUpdate) RemoveInventoryIDs(ids ...int) *PlayerUpdate {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventory removes "inventory" edges to InventoryItem entities.
func (_u *PlayerUpdate) RemoveInventory(v ...*InventoryItem) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// ClearNpcRelationships clears all "npc_relationships" edges to the PlayerNPCRelationship entity.
func (_u *PlayerUpdate) ClearNpcRelationships() *PlayerUpdate {
	_u.mutation.ClearNpcRelationships()
	return _u
}

// RemoveNpcRelationshipIDs removes the "npc_relationships" edge to PlayerNPCRelationship entities by IDs.
func (_u *PlayerUpdate) RemoveNpcRelationshipIDs(ids ...int) *PlayerUpdate {
	_u.mutation.RemoveNpcRelationshipIDs(ids...)
	return _u
}

// RemoveNpcRelationships removes "npc_relationships" edges to PlayerNPCRelationship entities.
func (_u *PlayerUpdate) RemoveNpcRelationships(v ...*PlayerNPCRelationship) *PlayerUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNpcRelationshipIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlayerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlayerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdate) check() error {
	if v, ok := _u.mutation.PlayerID(); ok {
		if err := player.PlayerIDValidator(v); err != nil {
			return &ValidationError{Name: "player_id", err: fmt.Errorf(`ent: validator failed for field "Player.player_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := player.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Player.password": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerName(); ok {
		_spec.SetField(player.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(player.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.QuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestStatesIDs(); len(nodes) > 0 && !_u.mutation.QuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryIDs(); len(nodes) > 0 && !_u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NpcRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNpcRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.NpcRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NpcRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlayerUpdateOne is the builder for updating a single Player entity.
type PlayerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlayerMutation
}

// SetPlayerID sets the "player_id" field.
func (_u *PlayerUpdateOne) SetPlayerID(v string) *PlayerUpdateOne {
	_u.mutation.SetPlayerID(v)
	return _u
}

// SetNillablePlayerID sets the "player_id" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePlayerID(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetPlayerID(*v)
	}
	return _u
}

// SetPlayerName sets the "player_name" field.
func (_u *PlayerUpdateOne) SetPlayerName(v string) *PlayerUpdateOne {
	_u.mutation.SetPlayerName(v)
	return _u
}

// SetNillablePlayerName sets the "player_name" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePlayerName(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetPlayerName(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *PlayerUpdateOne) SetPassword(v string) *PlayerUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *PlayerUpdateOne) SetNillablePassword(v *string) *PlayerUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// AddQuestStateIDs adds the "quest_states" edge to the PlayerQuestState entity by IDs.
func (_u *PlayerUpdateOne) AddQuestStateIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.AddQuestStateIDs(ids...)
	return _u
}

// AddQuestStates adds the "quest_states" edges to the PlayerQuestState entity.
func (_u *PlayerUpdateOne) AddQuestStates(v ...*PlayerQuestState) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddQuestStateIDs(ids...)
}

// AddInventoryIDs adds the "inventory" edge to the InventoryItem entity by IDs.
func (_u *PlayerUpdateOne) AddInventoryIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.AddInventoryIDs(ids...)
	return _u
}

// AddInventory adds the "inventory" edges to the InventoryItem entity.
func (_u *PlayerUpdateOne) AddInventory(v ...*InventoryItem) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddInventoryIDs(ids...)
}

// AddNpcRelationshipIDs adds the "npc_relationships" edge to the PlayerNPCRelationship entity by IDs.
func (_u *PlayerUpdateOne) AddNpcRelationshipIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.AddNpcRelationshipIDs(ids...)
	return _u
}

// AddNpcRelationships adds the "npc_relationships" edges to the PlayerNPCRelationship entity.
func (_u *PlayerUpdateOne) AddNpcRelationships(v ...*PlayerNPCRelationship) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddNpcRelationshipIDs(ids...)
}

// Mutation returns the PlayerMutation object of the builder.
func (_u *PlayerUpdateOne) Mutation() *PlayerMutation {
	return _u.mutation
}

// ClearQuestStates clears all "quest_states" edges to the PlayerQuestState entity.
func (_u *PlayerUpdateOne) ClearQuestStates() *PlayerUpdateOne {
	_u.mutation.ClearQuestStates()
	return _u
}

// RemoveQuestStateIDs removes the "quest_states" edge to PlayerQuestState entities by IDs.
func (_u *PlayerUpdateOne) RemoveQuestStateIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.RemoveQuestStateIDs(ids...)
	return _u
}

// RemoveQuestStates removes "quest_states" edges to PlayerQuestState entities.
func (_u *PlayerUpdateOne) RemoveQuestStates(v ...*PlayerQuestState) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveQuestStateIDs(ids...)
}

// ClearInventory clears all "inventory" edges to the InventoryItem entity.
func (_u *PlayerUpdateOne) ClearInventory() *PlayerUpdateOne {
	_u.mutation.ClearInventory()
	return _u
}

// RemoveInventoryIDs removes the "inventory" edge to InventoryItem entities by IDs.
func (_u *PlayerUpdateOne) RemoveInventoryIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.RemoveInventoryIDs(ids...)
	return _u
}

// RemoveInventory removes "inventory" edges to InventoryItem entities.
func (_u *PlayerUpdateOne) RemoveInventory(v ...*InventoryItem) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveInventoryIDs(ids...)
}

// ClearNpcRelationships clears all "npc_relationships" edges to the PlayerNPCRelationship entity.
func (_u *PlayerUpdateOne) ClearNpcRelationships() *PlayerUpdateOne {
	_u.mutation.ClearNpcRelationships()
	return _u
}

// RemoveNpcRelationshipIDs removes the "npc_relationships" edge to PlayerNPCRelationship entities by IDs.
func (_u *PlayerUpdateOne) RemoveNpcRelationshipIDs(ids ...int) *PlayerUpdateOne {
	_u.mutation.RemoveNpcRelationshipIDs(ids...)
	return _u
}

// RemoveNpcRelationships removes "npc_relationships" edges to PlayerNPCRelationship entities.
func (_u *PlayerUpdateOne) RemoveNpcRelationships(v ...*PlayerNPCRelationship) *PlayerUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveNpcRelationshipIDs(ids...)
}

// Where appends a list predicates to the PlayerUpdate builder.
func (_u *PlayerUpdateOne) Where(ps ...predicate.Player) *PlayerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlayerUpdateOne) Select(field string, fields ...string) *PlayerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Player entity.
func (_u *PlayerUpdateOne) Save(ctx context.Context) (*Player, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlayerUpdateOne) SaveX(ctx context.Context) *Player {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlayerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlayerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlayerUpdateOne) check() error {
	if v, ok := _u.mutation.PlayerID(); ok {
		if err := player.PlayerIDValidator(v); err != nil {
			return &ValidationError{Name: "player_id", err: fmt.Errorf(`ent: validator failed for field "Player.player_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := player.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Player.password": %w`, err)}
		}
	}
	return nil
}

func (_u *PlayerUpdateOne) sqlSave(ctx context.Context) (_node *Player, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(player.Table, player.Columns, sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Player.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, player.FieldID)
		for _, f := range fields {
			if !player.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != player.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PlayerID(); ok {
		_spec.SetField(player.FieldPlayerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PlayerName(); ok {
		_spec.SetField(player.FieldPlayerName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(player.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.QuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedQuestStatesIDs(); len(nodes) > 0 && !_u.mutation.QuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.QuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.QuestStatesTable,
			Columns: []string{player.QuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedInventoryIDs(); len(nodes) > 0 && !_u.mutation.InventoryCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.InventoryIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.InventoryTable,
			Columns: []string{player.InventoryColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(inventoryitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.NpcRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedNpcRelationshipsIDs(); len(nodes) > 0 && !_u.mutation.NpcRelationshipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.NpcRelationshipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   player.NpcRelationshipsTable,
			Columns: []string{player.NpcRelationshipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Player{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{player.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
