// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/npc"
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playernpcrelationship"
	"agentic-npc-backend/internal/db/ent/predicate"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlayerNPCRelationshipQuery is the builder for querying PlayerNPCRelationship entities.
type PlayerNPCRelationshipQuery struct {
	config
	ctx        *QueryContext
	order      []playernpcrelationship.OrderOption
	inters     []Interceptor
	predicates []predicate.PlayerNPCRelationship
	withPlayer *PlayerQuery
	withNpc    *NPCQuery
	withFKs    bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PlayerNPCRelationshipQuery builder.
func (_q *PlayerNPCRelationshipQuery) Where(ps ...predicate.PlayerNPCRelationship) *PlayerNPCRelationshipQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PlayerNPCRelationshipQuery) Limit(limit int) *PlayerNPCRelationshipQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PlayerNPCRelationshipQuery) Offset(offset int) *PlayerNPCRelationshipQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PlayerNPCRelationshipQuery) Unique(unique bool) *PlayerNPCRelationshipQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PlayerNPCRelationshipQuery) Order(o ...playernpcrelationship.OrderOption) *PlayerNPCRelationshipQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlayer chains the current query on the "player" edge.
func (_q *PlayerNPCRelationshipQuery) QueryPlayer() *PlayerQuery {
	query := (&PlayerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(playernpcrelationship.Table, playernpcrelationship.FieldID, selector),
			sqlgraph.To(player.Table, player.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, playernpcrelationship.PlayerTable, playernpcrelationship.PlayerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryNpc chains the current query on the "npc" edge.
func (_q *PlayerNPCRelationshipQuery) QueryNpc() *NPCQuery {
	query := (&NPCClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(playernpcrelationship.Table, playernpcrelationship.FieldID, selector),
			sqlgraph.To(npc.Table, npc.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, playernpcrelationship.NpcTable, playernpcrelationship.NpcColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PlayerNPCRelationship entity from the query.
// Returns a *NotFoundError when no PlayerNPCRelationship was found.
func (_q *PlayerNPCRelationshipQuery) First(ctx context.Context) (*PlayerNPCRelationship, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{playernpcrelationship.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) FirstX(ctx context.Context) *PlayerNPCRelationship {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PlayerNPCRelationship ID from the query.
// Returns a *NotFoundError when no PlayerNPCRelationship ID was found.
func (_q *PlayerNPCRelationshipQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{playernpcrelationship.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PlayerNPCRelationship entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PlayerNPCRelationship entity is found.
// Returns a *NotFoundError when no PlayerNPCRelationship entities are found.
func (_q *PlayerNPCRelationshipQuery) Only(ctx context.Context) (*PlayerNPCRelationship, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{playernpcrelationship.Label}
	default:
		return nil, &NotSingularError{playernpcrelationship.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) OnlyX(ctx context.Context) *PlayerNPCRelationship {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PlayerNPCRelationship ID in the query.
// Returns a *NotSingularError when more than one PlayerNPCRelationship ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PlayerNPCRelationshipQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{playernpcrelationship.Label}
	default:
		err = &NotSingularError{playernpcrelationship.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PlayerNPCRelationships.
func (_q *PlayerNPCRelationshipQuery) All(ctx context.Context) ([]*PlayerNPCRelationship, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PlayerNPCRelationship, *PlayerNPCRelationshipQuery]()
	return withInterceptors[[]*PlayerNPCRelationship](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) AllX(ctx context.Context) []*PlayerNPCRelationship {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PlayerNPCRelationship IDs.
func (_q *PlayerNPCRelationshipQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(playernpcrelationship.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PlayerNPCRelationshipQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PlayerNPCRelationshipQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PlayerNPCRelationshipQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PlayerNPCRelationshipQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PlayerNPCRelationshipQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PlayerNPCRelationshipQuery) Clone() *PlayerNPCRelationshipQuery {
	if _q == nil {
		return nil
	}
	return &PlayerNPCRelationshipQuery{
		config:     _q.config,
		ctx:        _q.ctx.Clone(),
		order:      append([]playernpcrelationship.OrderOption{}, _q.order...),
		inters:     append([]Interceptor{}, _q.inters...),
		predicates: append([]predicate.PlayerNPCRelationship{}, _q.predicates...),
		withPlayer: _q.withPlayer.Clone(),
		withNpc:    _q.withNpc.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlayer tells the query-builder to eager-load the nodes that are connected to
// the "player" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerNPCRelationshipQuery) WithPlayer(opts ...func(*PlayerQuery)) *PlayerNPCRelationshipQuery {
	query := (&PlayerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlayer = query
	return _q
}

// WithNpc tells the query-builder to eager-load the nodes that are connected to
// the "npc" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PlayerNPCRelationshipQuery) WithNpc(opts ...func(*NPCQuery)) *PlayerNPCRelationshipQuery {
	query := (&NPCClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withNpc = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TrustLevel float64 `json:"trust_level,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PlayerNPCRelationship.Query().
//		GroupBy(playernpcrelationship.FieldTrustLevel).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PlayerNPCRelationshipQuery) GroupBy(field string, fields ...string) *PlayerNPCRelationshipGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PlayerNPCRelationshipGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = playernpcrelationship.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TrustLevel float64 `json:"trust_level,omitempty"`
//	}
//
//	client.PlayerNPCRelationship.Query().
//		Select(playernpcrelationship.FieldTrustLevel).
//		Scan(ctx, &v)
func (_q *PlayerNPCRelationshipQuery) Select(fields ...string) *PlayerNPCRelationshipSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PlayerNPCRelationshipSelect{PlayerNPCRelationshipQuery: _q}
	sbuild.label = playernpcrelationship.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PlayerNPCRelationshipSelect configured with the given aggregations.
func (_q *PlayerNPCRelationshipQuery) Aggregate(fns ...AggregateFunc) *PlayerNPCRelationshipSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PlayerNPCRelationshipQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !playernpcrelationship.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PlayerNPCRelationshipQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PlayerNPCRelationship, error) {
	var (
		nodes       = []*PlayerNPCRelationship{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withPlayer != nil,
			_q.withNpc != nil,
		}
	)
	if _q.withPlayer != nil || _q.withNpc != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, playernpcrelationship.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PlayerNPCRelationship).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PlayerNPCRelationship{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlayer; query != nil {
		if err := _q.loadPlayer(ctx, query, nodes, nil,
			func(n *PlayerNPCRelationship, e *Player) { n.Edges.Player = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withNpc; query != nil {
		if err := _q.loadNpc(ctx, query, nodes, nil,
			func(n *PlayerNPCRelationship, e *NPC) { n.Edges.Npc = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PlayerNPCRelationshipQuery) loadPlayer(ctx context.Context, query *PlayerQuery, nodes []*PlayerNPCRelationship, init func(*PlayerNPCRelationship), assign func(*PlayerNPCRelationship, *Player)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PlayerNPCRelationship)
	for i := range nodes {
		if nodes[i].player_npc_relationships == nil {
			continue
		}
		fk := *nodes[i].player_npc_relationships
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(player.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "player_npc_relationships" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PlayerNPCRelationshipQuery) loadNpc(ctx context.Context, query *NPCQuery, nodes []*PlayerNPCRelationship, init func(*PlayerNPCRelationship), assign func(*PlayerNPCRelationship, *NPC)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*PlayerNPCRelationship)
	for i := range nodes {
		if nodes[i].npc_player_relationships == nil {
			continue
		}
		fk := *nodes[i].npc_player_relationships
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(npc.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "npc_player_relationships" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PlayerNPCRelationshipQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PlayerNPCRelationshipQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(playernpcrelationship.Table, playernpcrelationship.Columns, sqlgraph.NewFieldSpec(playernpcrelationship.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, playernpcrelationship.FieldID)
		for i := range fields {
			if fields[i] != playernpcrelationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PlayerNPCRelationshipQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(playernpcrelationship.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = playernpcrelationship.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PlayerNPCRelationshipGroupBy is the group-by builder for PlayerNPCRelationship entities.
type PlayerNPCRelationshipGroupBy struct {
	selector
	build *PlayerNPCRelationshipQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PlayerNPCRelationshipGroupBy) Aggregate(fns ...AggregateFunc) *PlayerNPCRelationshipGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PlayerNPCRelationshipGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayerNPCRelationshipQuery, *PlayerNPCRelationshipGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PlayerNPCRelationshipGroupBy) sqlScan(ctx context.Context, root *PlayerNPCRelationshipQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PlayerNPCRelationshipSelect is the builder for selecting fields of PlayerNPCRelationship entities.
type PlayerNPCRelationshipSelect struct {
	*PlayerNPCRelationshipQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PlayerNPCRelationshipSelect) Aggregate(fns ...AggregateFunc) *PlayerNPCRelationshipSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PlayerNPCRelationshipSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PlayerNPCRelationshipQuery, *PlayerNPCRelationshipSelect](ctx, _s.PlayerNPCRelationshipQuery, _s, _s.inters, v)
}

func (_s *PlayerNPCRelationshipSelect) sqlScan(ctx context.Context, root *PlayerNPCRelationshipQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
