// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/quest"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// PlayerQuestState is the model entity for the PlayerQuestState schema.
type PlayerQuestState struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// The static ID of the quest (from gamedata)
	QuestIdentifier string `json:"quest_identifier,omitempty"`
	// CurrentStep holds the value of the "current_step" field.
	CurrentStep int `json:"current_step,omitempty"`
	// IsCompleted holds the value of the "is_completed" field.
	IsCompleted bool `json:"is_completed,omitempty"`
	// CompletionRate holds the value of the "completion_rate" field.
	CompletionRate float32 `json:"completion_rate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PlayerQuestStateQuery when eager-loading is set.
	Edges                     PlayerQuestStateEdges `json:"edges"`
	player_quest_states       *uuid.UUID
	quest_player_quest_states *string
	selectValues              sql.SelectValues
}

// PlayerQuestStateEdges holds the relations/edges for other nodes in the graph.
type PlayerQuestStateEdges struct {
	// Player holds the value of the player edge.
	Player *Player `json:"player,omitempty"`
	// Quest holds the value of the quest edge.
	Quest *Quest `json:"quest,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// PlayerOrErr returns the Player value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerQuestStateEdges) PlayerOrErr() (*Player, error) {
	if e.Player != nil {
		return e.Player, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: player.Label}
	}
	return nil, &NotLoadedError{edge: "player"}
}

// QuestOrErr returns the Quest value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PlayerQuestStateEdges) QuestOrErr() (*Quest, error) {
	if e.Quest != nil {
		return e.Quest, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: quest.Label}
	}
	return nil, &NotLoadedError{edge: "quest"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PlayerQuestState) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case playerqueststate.FieldIsCompleted:
			values[i] = new(sql.NullBool)
		case playerqueststate.FieldCompletionRate:
			values[i] = new(sql.NullFloat64)
		case playerqueststate.FieldID, playerqueststate.FieldCurrentStep:
			values[i] = new(sql.NullInt64)
		case playerqueststate.FieldQuestIdentifier:
			values[i] = new(sql.NullString)
		case playerqueststate.ForeignKeys[0]: // player_quest_states
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case playerqueststate.ForeignKeys[1]: // quest_player_quest_states
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PlayerQuestState fields.
func (_m *PlayerQuestState) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case playerqueststate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case playerqueststate.FieldQuestIdentifier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quest_identifier", values[i])
			} else if value.Valid {
				_m.QuestIdentifier = value.String
			}
		case playerqueststate.FieldCurrentStep:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field current_step", values[i])
			} else if value.Valid {
				_m.CurrentStep = int(value.Int64)
			}
		case playerqueststate.FieldIsCompleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_completed", values[i])
			} else if value.Valid {
				_m.IsCompleted = value.Bool
			}
		case playerqueststate.FieldCompletionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field completion_rate", values[i])
			} else if value.Valid {
				_m.CompletionRate = float32(value.Float64)
			}
		case playerqueststate.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field player_quest_states", values[i])
			} else if value.Valid {
				_m.player_quest_states = new(uuid.UUID)
				*_m.player_quest_states = *value.S.(*uuid.UUID)
			}
		case playerqueststate.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quest_player_quest_states", values[i])
			} else if value.Valid {
				_m.quest_player_quest_states = new(string)
				*_m.quest_player_quest_states = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PlayerQuestState.
// This includes values selected through modifiers, order, etc.
func (_m *PlayerQuestState) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlayer queries the "player" edge of the PlayerQuestState entity.
func (_m *PlayerQuestState) QueryPlayer() *PlayerQuery {
	return NewPlayerQuestStateClient(_m.config).QueryPlayer(_m)
}

// QueryQuest queries the "quest" edge of the PlayerQuestState entity.
func (_m *PlayerQuestState) QueryQuest() *QuestQuery {
	return NewPlayerQuestStateClient(_m.config).QueryQuest(_m)
}

// Update returns a builder for updating this PlayerQuestState.
// Note that you need to call PlayerQuestState.Unwrap() before calling this method if this PlayerQuestState
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PlayerQuestState) Update() *PlayerQuestStateUpdateOne {
	return NewPlayerQuestStateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PlayerQuestState entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PlayerQuestState) Unwrap() *PlayerQuestState {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PlayerQuestState is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PlayerQuestState) String() string {
	var builder strings.Builder
	builder.WriteString("PlayerQuestState(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quest_identifier=")
	builder.WriteString(_m.QuestIdentifier)
	builder.WriteString(", ")
	builder.WriteString("current_step=")
	builder.WriteString(fmt.Sprintf("%v", _m.CurrentStep))
	builder.WriteString(", ")
	builder.WriteString("is_completed=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCompleted))
	builder.WriteString(", ")
	builder.WriteString("completion_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompletionRate))
	builder.WriteByte(')')
	return builder.String()
}

// PlayerQuestStates is a parsable slice of PlayerQuestState.
type PlayerQuestStates []*PlayerQuestState
