// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/player"
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/quest"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// PlayerQuestStateCreate is the builder for creating a PlayerQuestState entity.
type PlayerQuestStateCreate struct {
	config
	mutation *PlayerQuestStateMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetQuestIdentifier sets the "quest_identifier" field.
func (_c *PlayerQuestStateCreate) SetQuestIdentifier(v string) *PlayerQuestStateCreate {
	_c.mutation.SetQuestIdentifier(v)
	return _c
}

// SetCurrentStep sets the "current_step" field.
func (_c *PlayerQuestStateCreate) SetCurrentStep(v int) *PlayerQuestStateCreate {
	_c.mutation.SetCurrentStep(v)
	return _c
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_c *PlayerQuestStateCreate) SetNillableCurrentStep(v *int) *PlayerQuestStateCreate {
	if v != nil {
		_c.SetCurrentStep(*v)
	}
	return _c
}

// SetIsCompleted sets the "is_completed" field.
func (_c *PlayerQuestStateCreate) SetIsCompleted(v bool) *PlayerQuestStateCreate {
	_c.mutation.SetIsCompleted(v)
	return _c
}

// SetNillableIsCompleted sets the "is_completed" field if the given value is not nil.
func (_c *PlayerQuestStateCreate) SetNillableIsCompleted(v *bool) *PlayerQuestStateCreate {
	if v != nil {
		_c.SetIsCompleted(*v)
	}
	return _c
}

// SetCompletionRate sets the "completion_rate" field.
func (_c *PlayerQuestStateCreate) SetCompletionRate(v float32) *PlayerQuestStateCreate {
	_c.mutation.SetCompletionRate(v)
	return _c
}

// SetNillableCompletionRate sets the "completion_rate" field if the given value is not nil.
func (_c *PlayerQuestStateCreate) SetNillableCompletionRate(v *float32) *PlayerQuestStateCreate {
	if v != nil {
		_c.SetCompletionRate(*v)
	}
	return _c
}

// SetPlayerID sets the "player" edge to the Player entity by ID.
func (_c *PlayerQuestStateCreate) SetPlayerID(id uuid.UUID) *PlayerQuestStateCreate {
	_c.mutation.SetPlayerID(id)
	return _c
}

// SetPlayer sets the "player" edge to the Player entity.
func (_c *PlayerQuestStateCreate) SetPlayer(v *Player) *PlayerQuestStateCreate {
	return _c.SetPlayerID(v.ID)
}

// SetQuestID sets the "quest" edge to the Quest entity by ID.
func (_c *PlayerQuestStateCreate) SetQuestID(id string) *PlayerQuestStateCreate {
	_c.mutation.SetQuestID(id)
	return _c
}

// SetQuest sets the "quest" edge to the Quest entity.
func (_c *PlayerQuestStateCreate) SetQuest(v *Quest) *PlayerQuestStateCreate {
	return _c.SetQuestID(v.ID)
}

// Mutation returns the PlayerQuestStateMutation object of the builder.
func (_c *PlayerQuestStateCreate) Mutation() *PlayerQuestStateMutation {
	return _c.mutation
}

// Save creates the PlayerQuestState in the database.
func (_c *PlayerQuestStateCreate) Save(ctx context.Context) (*PlayerQuestState, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PlayerQuestStateCreate) SaveX(ctx context.Context) *PlayerQuestState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerQuestStateCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerQuestStateCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PlayerQuestStateCreate) defaults() {
	if _, ok := _c.mutation.CurrentStep(); !ok {
		v := playerqueststate.DefaultCurrentStep
		_c.mutation.SetCurrentStep(v)
	}
	if _, ok := _c.mutation.IsCompleted(); !ok {
		v := playerqueststate.DefaultIsCompleted
		_c.mutation.SetIsCompleted(v)
	}
	if _, ok := _c.mutation.CompletionRate(); !ok {
		v := playerqueststate.DefaultCompletionRate
		_c.mutation.SetCompletionRate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PlayerQuestStateCreate) check() error {
	if _, ok := _c.mutation.QuestIdentifier(); !ok {
		return &ValidationError{Name: "quest_identifier", err: errors.New(`ent: missing required field "PlayerQuestState.quest_identifier"`)}
	}
	if v, ok := _c.mutation.QuestIdentifier(); ok {
		if err := playerqueststate.QuestIdentifierValidator(v); err != nil {
			return &ValidationError{Name: "quest_identifier", err: fmt.Errorf(`ent: validator failed for field "PlayerQuestState.quest_identifier": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentStep(); !ok {
		return &ValidationError{Name: "current_step", err: errors.New(`ent: missing required field "PlayerQuestState.current_step"`)}
	}
	if _, ok := _c.mutation.IsCompleted(); !ok {
		return &ValidationError{Name: "is_completed", err: errors.New(`ent: missing required field "PlayerQuestState.is_completed"`)}
	}
	if _, ok := _c.mutation.CompletionRate(); !ok {
		return &ValidationError{Name: "completion_rate", err: errors.New(`ent: missing required field "PlayerQuestState.completion_rate"`)}
	}
	if len(_c.mutation.PlayerIDs()) == 0 {
		return &ValidationError{Name: "player", err: errors.New(`ent: missing required edge "PlayerQuestState.player"`)}
	}
	if len(_c.mutation.QuestIDs()) == 0 {
		return &ValidationError{Name: "quest", err: errors.New(`ent: missing required edge "PlayerQuestState.quest"`)}
	}
	return nil
}

func (_c *PlayerQuestStateCreate) sqlSave(ctx context.Context) (*PlayerQuestState, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PlayerQuestStateCreate) createSpec() (*PlayerQuestState, *sqlgraph.CreateSpec) {
	var (
		_node = &PlayerQuestState{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(playerqueststate.Table, sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.QuestIdentifier(); ok {
		_spec.SetField(playerqueststate.FieldQuestIdentifier, field.TypeString, value)
		_node.QuestIdentifier = value
	}
	if value, ok := _c.mutation.CurrentStep(); ok {
		_spec.SetField(playerqueststate.FieldCurrentStep, field.TypeInt, value)
		_node.CurrentStep = value
	}
	if value, ok := _c.mutation.IsCompleted(); ok {
		_spec.SetField(playerqueststate.FieldIsCompleted, field.TypeBool, value)
		_node.IsCompleted = value
	}
	if value, ok := _c.mutation.CompletionRate(); ok {
		_spec.SetField(playerqueststate.FieldCompletionRate, field.TypeFloat32, value)
		_node.CompletionRate = value
	}
	if nodes := _c.mutation.PlayerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.PlayerTable,
			Columns: []string{playerqueststate.PlayerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(player.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.player_quest_states = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.QuestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   playerqueststate.QuestTable,
			Columns: []string{playerqueststate.QuestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.quest_player_quest_states = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlayerQuestState.Create().
//		SetQuestIdentifier(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerQuestStateUpsert) {
//			SetQuestIdentifier(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerQuestStateCreate) OnConflict(opts ...sql.ConflictOption) *PlayerQuestStateUpsertOne {
	_c.conflict = opts
	return &PlayerQuestStateUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerQuestStateCreate) OnConflictColumns(columns ...string) *PlayerQuestStateUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerQuestStateUpsertOne{
		create: _c,
	}
}

type (
	// PlayerQuestStateUpsertOne is the builder for "upsert"-ing
	//  one PlayerQuestState node.
	PlayerQuestStateUpsertOne struct {
		create *PlayerQuestStateCreate
	}

	// PlayerQuestStateUpsert is the "OnConflict" setter.
	PlayerQuestStateUpsert struct {
		*sql.UpdateSet
	}
)

// SetQuestIdentifier sets the "quest_identifier" field.
func (u *PlayerQuestStateUpsert) SetQuestIdentifier(v string) *PlayerQuestStateUpsert {
	u.Set(playerqueststate.FieldQuestIdentifier, v)
	return u
}

// UpdateQuestIdentifier sets the "quest_identifier" field to the value that was provided on create.
func (u *PlayerQuestStateUpsert) UpdateQuestIdentifier() *PlayerQuestStateUpsert {
	u.SetExcluded(playerqueststate.FieldQuestIdentifier)
	return u
}

// SetCurrentStep sets the "current_step" field.
func (u *PlayerQuestStateUpsert) SetCurrentStep(v int) *PlayerQuestStateUpsert {
	u.Set(playerqueststate.FieldCurrentStep, v)
	return u
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *PlayerQuestStateUpsert) UpdateCurrentStep() *PlayerQuestStateUpsert {
	u.SetExcluded(playerqueststate.FieldCurrentStep)
	return u
}

// AddCurrentStep adds v to the "current_step" field.
func (u *PlayerQuestStateUpsert) AddCurrentStep(v int) *PlayerQuestStateUpsert {
	u.Add(playerqueststate.FieldCurrentStep, v)
	return u
}

// SetIsCompleted sets the "is_completed" field.
func (u *PlayerQuestStateUpsert) SetIsCompleted(v bool) *PlayerQuestStateUpsert {
	u.Set(playerqueststate.FieldIsCompleted, v)
	return u
}

// UpdateIsCompleted sets the "is_completed" field to the value that was provided on create.
func (u *PlayerQuestStateUpsert) UpdateIsCompleted() *PlayerQuestStateUpsert {
	u.SetExcluded(playerqueststate.FieldIsCompleted)
	return u
}

// SetCompletionRate sets the "completion_rate" field.
func (u *PlayerQuestStateUpsert) SetCompletionRate(v float32) *PlayerQuestStateUpsert {
	u.Set(playerqueststate.FieldCompletionRate, v)
	return u
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *PlayerQuestStateUpsert) UpdateCompletionRate() *PlayerQuestStateUpsert {
	u.SetExcluded(playerqueststate.FieldCompletionRate)
	return u
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *PlayerQuestStateUpsert) AddCompletionRate(v float32) *PlayerQuestStateUpsert {
	u.Add(playerqueststate.FieldCompletionRate, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlayerQuestStateUpsertOne) UpdateNewValues() *PlayerQuestStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PlayerQuestStateUpsertOne) Ignore() *PlayerQuestStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerQuestStateUpsertOne) DoNothing() *PlayerQuestStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerQuestStateCreate.OnConflict
// documentation for more info.
func (u *PlayerQuestStateUpsertOne) Update(set func(*PlayerQuestStateUpsert)) *PlayerQuestStateUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerQuestStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuestIdentifier sets the "quest_identifier" field.
func (u *PlayerQuestStateUpsertOne) SetQuestIdentifier(v string) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetQuestIdentifier(v)
	})
}

// UpdateQuestIdentifier sets the "quest_identifier" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertOne) UpdateQuestIdentifier() *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateQuestIdentifier()
	})
}

// SetCurrentStep sets the "current_step" field.
func (u *PlayerQuestStateUpsertOne) SetCurrentStep(v int) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetCurrentStep(v)
	})
}

// AddCurrentStep adds v to the "current_step" field.
func (u *PlayerQuestStateUpsertOne) AddCurrentStep(v int) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.AddCurrentStep(v)
	})
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertOne) UpdateCurrentStep() *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateCurrentStep()
	})
}

// SetIsCompleted sets the "is_completed" field.
func (u *PlayerQuestStateUpsertOne) SetIsCompleted(v bool) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetIsCompleted(v)
	})
}

// UpdateIsCompleted sets the "is_completed" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertOne) UpdateIsCompleted() *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateIsCompleted()
	})
}

// SetCompletionRate sets the "completion_rate" field.
func (u *PlayerQuestStateUpsertOne) SetCompletionRate(v float32) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetCompletionRate(v)
	})
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *PlayerQuestStateUpsertOne) AddCompletionRate(v float32) *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.AddCompletionRate(v)
	})
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertOne) UpdateCompletionRate() *PlayerQuestStateUpsertOne {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateCompletionRate()
	})
}

// Exec executes the query.
func (u *PlayerQuestStateUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerQuestStateCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerQuestStateUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PlayerQuestStateUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PlayerQuestStateUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PlayerQuestStateCreateBulk is the builder for creating many PlayerQuestState entities in bulk.
type PlayerQuestStateCreateBulk struct {
	config
	err      error
	builders []*PlayerQuestStateCreate
	conflict []sql.ConflictOption
}

// Save creates the PlayerQuestState entities in the database.
func (_c *PlayerQuestStateCreateBulk) Save(ctx context.Context) ([]*PlayerQuestState, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PlayerQuestState, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PlayerQuestStateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PlayerQuestStateCreateBulk) SaveX(ctx context.Context) []*PlayerQuestState {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PlayerQuestStateCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PlayerQuestStateCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PlayerQuestState.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PlayerQuestStateUpsert) {
//			SetQuestIdentifier(v+v).
//		}).
//		Exec(ctx)
func (_c *PlayerQuestStateCreateBulk) OnConflict(opts ...sql.ConflictOption) *PlayerQuestStateUpsertBulk {
	_c.conflict = opts
	return &PlayerQuestStateUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PlayerQuestStateCreateBulk) OnConflictColumns(columns ...string) *PlayerQuestStateUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PlayerQuestStateUpsertBulk{
		create: _c,
	}
}

// PlayerQuestStateUpsertBulk is the builder for "upsert"-ing
// a bulk of PlayerQuestState nodes.
type PlayerQuestStateUpsertBulk struct {
	create *PlayerQuestStateCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PlayerQuestStateUpsertBulk) UpdateNewValues() *PlayerQuestStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PlayerQuestState.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PlayerQuestStateUpsertBulk) Ignore() *PlayerQuestStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PlayerQuestStateUpsertBulk) DoNothing() *PlayerQuestStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PlayerQuestStateCreateBulk.OnConflict
// documentation for more info.
func (u *PlayerQuestStateUpsertBulk) Update(set func(*PlayerQuestStateUpsert)) *PlayerQuestStateUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PlayerQuestStateUpsert{UpdateSet: update})
	}))
	return u
}

// SetQuestIdentifier sets the "quest_identifier" field.
func (u *PlayerQuestStateUpsertBulk) SetQuestIdentifier(v string) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetQuestIdentifier(v)
	})
}

// UpdateQuestIdentifier sets the "quest_identifier" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertBulk) UpdateQuestIdentifier() *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateQuestIdentifier()
	})
}

// SetCurrentStep sets the "current_step" field.
func (u *PlayerQuestStateUpsertBulk) SetCurrentStep(v int) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetCurrentStep(v)
	})
}

// AddCurrentStep adds v to the "current_step" field.
func (u *PlayerQuestStateUpsertBulk) AddCurrentStep(v int) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.AddCurrentStep(v)
	})
}

// UpdateCurrentStep sets the "current_step" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertBulk) UpdateCurrentStep() *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateCurrentStep()
	})
}

// SetIsCompleted sets the "is_completed" field.
func (u *PlayerQuestStateUpsertBulk) SetIsCompleted(v bool) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetIsCompleted(v)
	})
}

// UpdateIsCompleted sets the "is_completed" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertBulk) UpdateIsCompleted() *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateIsCompleted()
	})
}

// SetCompletionRate sets the "completion_rate" field.
func (u *PlayerQuestStateUpsertBulk) SetCompletionRate(v float32) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.SetCompletionRate(v)
	})
}

// AddCompletionRate adds v to the "completion_rate" field.
func (u *PlayerQuestStateUpsertBulk) AddCompletionRate(v float32) *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.AddCompletionRate(v)
	})
}

// UpdateCompletionRate sets the "completion_rate" field to the value that was provided on create.
func (u *PlayerQuestStateUpsertBulk) UpdateCompletionRate() *PlayerQuestStateUpsertBulk {
	return u.Update(func(s *PlayerQuestStateUpsert) {
		s.UpdateCompletionRate()
	})
}

// Exec executes the query.
func (u *PlayerQuestStateUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PlayerQuestStateCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PlayerQuestStateCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PlayerQuestStateUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
