// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/quest"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestCreate is the builder for creating a Quest entity.
type QuestCreate struct {
	config
	mutation *QuestMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *QuestCreate) SetName(v string) *QuestCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_c *QuestCreate) SetNillableName(v *string) *QuestCreate {
	if v != nil {
		_c.SetName(*v)
	}
	return _c
}

// SetStaticDataPath sets the "static_data_path" field.
func (_c *QuestCreate) SetStaticDataPath(v string) *QuestCreate {
	_c.mutation.SetStaticDataPath(v)
	return _c
}

// SetID sets the "id" field.
func (_c *QuestCreate) SetID(v string) *QuestCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddPlayerQuestStateIDs adds the "player_quest_states" edge to the PlayerQuestState entity by IDs.
func (_c *QuestCreate) AddPlayerQuestStateIDs(ids ...int) *QuestCreate {
	_c.mutation.AddPlayerQuestStateIDs(ids...)
	return _c
}

// AddPlayerQuestStates adds the "player_quest_states" edges to the PlayerQuestState entity.
func (_c *QuestCreate) AddPlayerQuestStates(v ...*PlayerQuestState) *QuestCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPlayerQuestStateIDs(ids...)
}

// Mutation returns the QuestMutation object of the builder.
func (_c *QuestCreate) Mutation() *QuestMutation {
	return _c.mutation
}

// Save creates the Quest in the database.
func (_c *QuestCreate) Save(ctx context.Context) (*Quest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QuestCreate) SaveX(ctx context.Context) *Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QuestCreate) defaults() {
	if _, ok := _c.mutation.Name(); !ok {
		v := quest.DefaultName
		_c.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QuestCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Quest.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := quest.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Quest.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.StaticDataPath(); !ok {
		return &ValidationError{Name: "static_data_path", err: errors.New(`ent: missing required field "Quest.static_data_path"`)}
	}
	if v, ok := _c.mutation.StaticDataPath(); ok {
		if err := quest.StaticDataPathValidator(v); err != nil {
			return &ValidationError{Name: "static_data_path", err: fmt.Errorf(`ent: validator failed for field "Quest.static_data_path": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := quest.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Quest.id": %w`, err)}
		}
	}
	return nil
}

func (_c *QuestCreate) sqlSave(ctx context.Context) (*Quest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Quest.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QuestCreate) createSpec() (*Quest, *sqlgraph.CreateSpec) {
	var (
		_node = &Quest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(quest.Table, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.StaticDataPath(); ok {
		_spec.SetField(quest.FieldStaticDataPath, field.TypeString, value)
		_node.StaticDataPath = value
	}
	if nodes := _c.mutation.PlayerQuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Quest.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *QuestCreate) OnConflict(opts ...sql.ConflictOption) *QuestUpsertOne {
	_c.conflict = opts
	return &QuestUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuestCreate) OnConflictColumns(columns ...string) *QuestUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuestUpsertOne{
		create: _c,
	}
}

type (
	// QuestUpsertOne is the builder for "upsert"-ing
	//  one Quest node.
	QuestUpsertOne struct {
		create *QuestCreate
	}

	// QuestUpsert is the "OnConflict" setter.
	QuestUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *QuestUpsert) SetName(v string) *QuestUpsert {
	u.Set(quest.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsert) UpdateName() *QuestUpsert {
	u.SetExcluded(quest.FieldName)
	return u
}

// SetStaticDataPath sets the "static_data_path" field.
func (u *QuestUpsert) SetStaticDataPath(v string) *QuestUpsert {
	u.Set(quest.FieldStaticDataPath, v)
	return u
}

// UpdateStaticDataPath sets the "static_data_path" field to the value that was provided on create.
func (u *QuestUpsert) UpdateStaticDataPath() *QuestUpsert {
	u.SetExcluded(quest.FieldStaticDataPath)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestUpsertOne) UpdateNewValues() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(quest.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QuestUpsertOne) Ignore() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestUpsertOne) DoNothing() *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestCreate.OnConflict
// documentation for more info.
func (u *QuestUpsertOne) Update(set func(*QuestUpsert)) *QuestUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *QuestUpsertOne) SetName(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateName() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateName()
	})
}

// SetStaticDataPath sets the "static_data_path" field.
func (u *QuestUpsertOne) SetStaticDataPath(v string) *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.SetStaticDataPath(v)
	})
}

// UpdateStaticDataPath sets the "static_data_path" field to the value that was provided on create.
func (u *QuestUpsertOne) UpdateStaticDataPath() *QuestUpsertOne {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateStaticDataPath()
	})
}

// Exec executes the query.
func (u *QuestUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QuestUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: QuestUpsertOne.ID is not supported by MySQL driver. Use QuestUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QuestUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QuestCreateBulk is the builder for creating many Quest entities in bulk.
type QuestCreateBulk struct {
	config
	err      error
	builders []*QuestCreate
	conflict []sql.ConflictOption
}

// Save creates the Quest entities in the database.
func (_c *QuestCreateBulk) Save(ctx context.Context) ([]*Quest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Quest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QuestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QuestCreateBulk) SaveX(ctx context.Context) []*Quest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QuestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QuestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Quest.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QuestUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *QuestCreateBulk) OnConflict(opts ...sql.ConflictOption) *QuestUpsertBulk {
	_c.conflict = opts
	return &QuestUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QuestCreateBulk) OnConflictColumns(columns ...string) *QuestUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QuestUpsertBulk{
		create: _c,
	}
}

// QuestUpsertBulk is the builder for "upsert"-ing
// a bulk of Quest nodes.
type QuestUpsertBulk struct {
	create *QuestCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(quest.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QuestUpsertBulk) UpdateNewValues() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(quest.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Quest.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QuestUpsertBulk) Ignore() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QuestUpsertBulk) DoNothing() *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QuestCreateBulk.OnConflict
// documentation for more info.
func (u *QuestUpsertBulk) Update(set func(*QuestUpsert)) *QuestUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QuestUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *QuestUpsertBulk) SetName(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateName() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateName()
	})
}

// SetStaticDataPath sets the "static_data_path" field.
func (u *QuestUpsertBulk) SetStaticDataPath(v string) *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.SetStaticDataPath(v)
	})
}

// UpdateStaticDataPath sets the "static_data_path" field to the value that was provided on create.
func (u *QuestUpsertBulk) UpdateStaticDataPath() *QuestUpsertBulk {
	return u.Update(func(s *QuestUpsert) {
		s.UpdateStaticDataPath()
	})
}

// Exec executes the query.
func (u *QuestUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QuestCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QuestCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QuestUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
