// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/playerqueststate"
	"agentic-npc-backend/internal/db/ent/predicate"
	"agentic-npc-backend/internal/db/ent/quest"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuestUpdate is the builder for updating Quest entities.
type QuestUpdate struct {
	config
	hooks    []Hook
	mutation *QuestMutation
}

// Where appends a list predicates to the QuestUpdate builder.
func (_u *QuestUpdate) Where(ps ...predicate.Quest) *QuestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *QuestUpdate) SetName(v string) *QuestUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableName(v *string) *QuestUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStaticDataPath sets the "static_data_path" field.
func (_u *QuestUpdate) SetStaticDataPath(v string) *QuestUpdate {
	_u.mutation.SetStaticDataPath(v)
	return _u
}

// SetNillableStaticDataPath sets the "static_data_path" field if the given value is not nil.
func (_u *QuestUpdate) SetNillableStaticDataPath(v *string) *QuestUpdate {
	if v != nil {
		_u.SetStaticDataPath(*v)
	}
	return _u
}

// AddPlayerQuestStateIDs adds the "player_quest_states" edge to the PlayerQuestState entity by IDs.
func (_u *QuestUpdate) AddPlayerQuestStateIDs(ids ...int) *QuestUpdate {
	_u.mutation.AddPlayerQuestStateIDs(ids...)
	return _u
}

// AddPlayerQuestStates adds the "player_quest_states" edges to the PlayerQuestState entity.
func (_u *QuestUpdate) AddPlayerQuestStates(v ...*PlayerQuestState) *QuestUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerQuestStateIDs(ids...)
}

// Mutation returns the QuestMutation object of the builder.
func (_u *QuestUpdate) Mutation() *QuestMutation {
	return _u.mutation
}

// ClearPlayerQuestStates clears all "player_quest_states" edges to the PlayerQuestState entity.
func (_u *QuestUpdate) ClearPlayerQuestStates() *QuestUpdate {
	_u.mutation.ClearPlayerQuestStates()
	return _u
}

// RemovePlayerQuestStateIDs removes the "player_quest_states" edge to PlayerQuestState entities by IDs.
func (_u *QuestUpdate) RemovePlayerQuestStateIDs(ids ...int) *QuestUpdate {
	_u.mutation.RemovePlayerQuestStateIDs(ids...)
	return _u
}

// RemovePlayerQuestStates removes "player_quest_states" edges to PlayerQuestState entities.
func (_u *QuestUpdate) RemovePlayerQuestStates(v ...*PlayerQuestState) *QuestUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerQuestStateIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *QuestUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *QuestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := quest.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Quest.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StaticDataPath(); ok {
		if err := quest.StaticDataPathValidator(v); err != nil {
			return &ValidationError{Name: "static_data_path", err: fmt.Errorf(`ent: validator failed for field "Quest.static_data_path": %w`, err)}
		}
	}
	return nil
}

func (_u *QuestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quest.Table, quest.Columns, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StaticDataPath(); ok {
		_spec.SetField(quest.FieldStaticDataPath, field.TypeString, value)
	}
	if _u.mutation.PlayerQuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayerQuestStatesIDs(); len(nodes) > 0 && !_u.mutation.PlayerQuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerQuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// QuestUpdateOne is the builder for updating a single Quest entity.
type QuestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *QuestMutation
}

// SetName sets the "name" field.
func (_u *QuestUpdateOne) SetName(v string) *QuestUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableName(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStaticDataPath sets the "static_data_path" field.
func (_u *QuestUpdateOne) SetStaticDataPath(v string) *QuestUpdateOne {
	_u.mutation.SetStaticDataPath(v)
	return _u
}

// SetNillableStaticDataPath sets the "static_data_path" field if the given value is not nil.
func (_u *QuestUpdateOne) SetNillableStaticDataPath(v *string) *QuestUpdateOne {
	if v != nil {
		_u.SetStaticDataPath(*v)
	}
	return _u
}

// AddPlayerQuestStateIDs adds the "player_quest_states" edge to the PlayerQuestState entity by IDs.
func (_u *QuestUpdateOne) AddPlayerQuestStateIDs(ids ...int) *QuestUpdateOne {
	_u.mutation.AddPlayerQuestStateIDs(ids...)
	return _u
}

// AddPlayerQuestStates adds the "player_quest_states" edges to the PlayerQuestState entity.
func (_u *QuestUpdateOne) AddPlayerQuestStates(v ...*PlayerQuestState) *QuestUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPlayerQuestStateIDs(ids...)
}

// Mutation returns the QuestMutation object of the builder.
func (_u *QuestUpdateOne) Mutation() *QuestMutation {
	return _u.mutation
}

// ClearPlayerQuestStates clears all "player_quest_states" edges to the PlayerQuestState entity.
func (_u *QuestUpdateOne) ClearPlayerQuestStates() *QuestUpdateOne {
	_u.mutation.ClearPlayerQuestStates()
	return _u
}

// RemovePlayerQuestStateIDs removes the "player_quest_states" edge to PlayerQuestState entities by IDs.
func (_u *QuestUpdateOne) RemovePlayerQuestStateIDs(ids ...int) *QuestUpdateOne {
	_u.mutation.RemovePlayerQuestStateIDs(ids...)
	return _u
}

// RemovePlayerQuestStates removes "player_quest_states" edges to PlayerQuestState entities.
func (_u *QuestUpdateOne) RemovePlayerQuestStates(v ...*PlayerQuestState) *QuestUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePlayerQuestStateIDs(ids...)
}

// Where appends a list predicates to the QuestUpdate builder.
func (_u *QuestUpdateOne) Where(ps ...predicate.Quest) *QuestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *QuestUpdateOne) Select(field string, fields ...string) *QuestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Quest entity.
func (_u *QuestUpdateOne) Save(ctx context.Context) (*Quest, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *QuestUpdateOne) SaveX(ctx context.Context) *Quest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *QuestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *QuestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *QuestUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := quest.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Quest.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StaticDataPath(); ok {
		if err := quest.StaticDataPathValidator(v); err != nil {
			return &ValidationError{Name: "static_data_path", err: fmt.Errorf(`ent: validator failed for field "Quest.static_data_path": %w`, err)}
		}
	}
	return nil
}

func (_u *QuestUpdateOne) sqlSave(ctx context.Context) (_node *Quest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(quest.Table, quest.Columns, sqlgraph.NewFieldSpec(quest.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Quest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quest.FieldID)
		for _, f := range fields {
			if !quest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != quest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(quest.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StaticDataPath(); ok {
		_spec.SetField(quest.FieldStaticDataPath, field.TypeString, value)
	}
	if _u.mutation.PlayerQuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPlayerQuestStatesIDs(); len(nodes) > 0 && !_u.mutation.PlayerQuestStatesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlayerQuestStatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   quest.PlayerQuestStatesTable,
			Columns: []string{quest.PlayerQuestStatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(playerqueststate.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Quest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{quest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
