// Code generated by ent, DO NOT EDIT.

package ent

import (
	"agentic-npc-backend/internal/db/ent/memory"
	"agentic-npc-backend/internal/db/ent/npc"
	"agentic-npc-backend/internal/db/ent/schema"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	memoryFields := schema.Memory{}.Fields()
	_ = memoryFields
	// memoryDescCreatedAt is the schema descriptor for created_at field.
	memoryDescCreatedAt := memoryFields[1].Descriptor()
	// memory.DefaultCreatedAt holds the default value on creation for the created_at field.
	memory.DefaultCreatedAt = memoryDescCreatedAt.Default.(func() time.Time)
	// memoryDescImportance is the schema descriptor for importance field.
	memoryDescImportance := memoryFields[5].Descriptor()
	// memory.DefaultImportance holds the default value on creation for the importance field.
	memory.DefaultImportance = memoryDescImportance.Default.(float64)
	npcFields := schema.NPC{}.Fields()
	_ = npcFields
	// npcDescName is the schema descriptor for name field.
	npcDescName := npcFields[1].Descriptor()
	// npc.NameValidator is a validator for the "name" field. It is called by the builders before save.
	npc.NameValidator = npcDescName.Validators[0].(func(string) error)
	// npcDescNpcType is the schema descriptor for npc_type field.
	npcDescNpcType := npcFields[2].Descriptor()
	// npc.DefaultNpcType holds the default value on creation for the npc_type field.
	npc.DefaultNpcType = npcDescNpcType.Default.(string)
	// npcDescEmotions is the schema descriptor for emotions field.
	npcDescEmotions := npcFields[3].Descriptor()
	// npc.DefaultEmotions holds the default value on creation for the emotions field.
	npc.DefaultEmotions = npcDescEmotions.Default.(*schema.EmotionState)
	// npcDescID is the schema descriptor for id field.
	npcDescID := npcFields[0].Descriptor()
	// npc.DefaultID holds the default value on creation for the id field.
	npc.DefaultID = npcDescID.Default.(func() uuid.UUID)
}
