// Code generated by ent, DO NOT EDIT.

package player

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the player type in the database.
	Label = "player"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPlayerID holds the string denoting the player_id field in the database.
	FieldPlayerID = "player_id"
	// FieldPlayerName holds the string denoting the player_name field in the database.
	FieldPlayerName = "player_name"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeQuestStates holds the string denoting the quest_states edge name in mutations.
	EdgeQuestStates = "quest_states"
	// EdgeInventory holds the string denoting the inventory edge name in mutations.
	EdgeInventory = "inventory"
	// EdgeNpcRelationships holds the string denoting the npc_relationships edge name in mutations.
	EdgeNpcRelationships = "npc_relationships"
	// Table holds the table name of the player in the database.
	Table = "players"
	// QuestStatesTable is the table that holds the quest_states relation/edge.
	QuestStatesTable = "player_quest_states"
	// QuestStatesInverseTable is the table name for the PlayerQuestState entity.
	// It exists in this package in order to avoid circular dependency with the "playerqueststate" package.
	QuestStatesInverseTable = "player_quest_states"
	// QuestStatesColumn is the table column denoting the quest_states relation/edge.
	QuestStatesColumn = "player_quest_states"
	// InventoryTable is the table that holds the inventory relation/edge.
	InventoryTable = "inventory_items"
	// InventoryInverseTable is the table name for the InventoryItem entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryitem" package.
	InventoryInverseTable = "inventory_items"
	// InventoryColumn is the table column denoting the inventory relation/edge.
	InventoryColumn = "player_inventory"
	// NpcRelationshipsTable is the table that holds the npc_relationships relation/edge.
	NpcRelationshipsTable = "player_npc_relationships"
	// NpcRelationshipsInverseTable is the table name for the PlayerNPCRelationship entity.
	// It exists in this package in order to avoid circular dependency with the "playernpcrelationship" package.
	NpcRelationshipsInverseTable = "player_npc_relationships"
	// NpcRelationshipsColumn is the table column denoting the npc_relationships relation/edge.
	NpcRelationshipsColumn = "player_npc_relationships"
)

// Columns holds all SQL columns for player fields.
var Columns = []string{
	FieldID,
	FieldPlayerID,
	FieldPlayerName,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PlayerIDValidator is a validator for the "player_id" field. It is called by the builders before save.
	PlayerIDValidator func(string) error
	// DefaultPlayerName holds the default value on creation for the "player_name" field.
	DefaultPlayerName string
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Player queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPlayerID orders the results by the player_id field.
func ByPlayerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerID, opts...).ToFunc()
}

// ByPlayerName orders the results by the player_name field.
func ByPlayerName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlayerName, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByQuestStatesCount orders the results by quest_states count.
func ByQuestStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newQuestStatesStep(), opts...)
	}
}

// ByQuestStates orders the results by quest_states terms.
func ByQuestStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newQuestStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByInventoryCount orders the results by inventory count.
func ByInventoryCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryStep(), opts...)
	}
}

// ByInventory orders the results by inventory terms.
func ByInventory(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByNpcRelationshipsCount orders the results by npc_relationships count.
func ByNpcRelationshipsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newNpcRelationshipsStep(), opts...)
	}
}

// ByNpcRelationships orders the results by npc_relationships terms.
func ByNpcRelationships(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newNpcRelationshipsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newQuestStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(QuestStatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, QuestStatesTable, QuestStatesColumn),
	)
}
func newInventoryStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryTable, InventoryColumn),
	)
}
func newNpcRelationshipsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(NpcRelationshipsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, NpcRelationshipsTable, NpcRelationshipsColumn),
	)
}
