// Code generated by ent, DO NOT EDIT.

package playernpcrelationship

import (
	"agentic-npc-backend/internal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLTE(FieldID, id))
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNpc applies the HasEdge predicate on the "npc" edge.
func HasNpc() predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NpcTable, NpcColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNpcWith applies the HasEdge predicate on the "npc" edge with a given conditions (other predicates).
func HasNpcWith(preds ...predicate.NPC) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := newNpcStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.NotPredicates(p))
}
