// Code generated by ent, DO NOT EDIT.

package playernpcrelationship

import (
	"agentic-npc-backend/internal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLTE(FieldID, id))
}

// TrustLevel applies equality check predicate on the "trust_level" field. It's identical to TrustLevelEQ.
func TrustLevel(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldTrustLevel, v))
}

// GiftCount applies equality check predicate on the "gift_count" field. It's identical to GiftCountEQ.
func GiftCount(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldGiftCount, v))
}

// TrustLevelEQ applies the EQ predicate on the "trust_level" field.
func TrustLevelEQ(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldTrustLevel, v))
}

// TrustLevelNEQ applies the NEQ predicate on the "trust_level" field.
func TrustLevelNEQ(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNEQ(FieldTrustLevel, v))
}

// TrustLevelIn applies the In predicate on the "trust_level" field.
func TrustLevelIn(vs ...float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldIn(FieldTrustLevel, vs...))
}

// TrustLevelNotIn applies the NotIn predicate on the "trust_level" field.
func TrustLevelNotIn(vs ...float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNotIn(FieldTrustLevel, vs...))
}

// TrustLevelGT applies the GT predicate on the "trust_level" field.
func TrustLevelGT(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGT(FieldTrustLevel, v))
}

// TrustLevelGTE applies the GTE predicate on the "trust_level" field.
func TrustLevelGTE(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGTE(FieldTrustLevel, v))
}

// TrustLevelLT applies the LT predicate on the "trust_level" field.
func TrustLevelLT(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLT(FieldTrustLevel, v))
}

// TrustLevelLTE applies the LTE predicate on the "trust_level" field.
func TrustLevelLTE(v float64) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLTE(FieldTrustLevel, v))
}

// GiftCountEQ applies the EQ predicate on the "gift_count" field.
func GiftCountEQ(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldEQ(FieldGiftCount, v))
}

// GiftCountNEQ applies the NEQ predicate on the "gift_count" field.
func GiftCountNEQ(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNEQ(FieldGiftCount, v))
}

// GiftCountIn applies the In predicate on the "gift_count" field.
func GiftCountIn(vs ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldIn(FieldGiftCount, vs...))
}

// GiftCountNotIn applies the NotIn predicate on the "gift_count" field.
func GiftCountNotIn(vs ...int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldNotIn(FieldGiftCount, vs...))
}

// GiftCountGT applies the GT predicate on the "gift_count" field.
func GiftCountGT(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGT(FieldGiftCount, v))
}

// GiftCountGTE applies the GTE predicate on the "gift_count" field.
func GiftCountGTE(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldGTE(FieldGiftCount, v))
}

// GiftCountLT applies the LT predicate on the "gift_count" field.
func GiftCountLT(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLT(FieldGiftCount, v))
}

// GiftCountLTE applies the LTE predicate on the "gift_count" field.
func GiftCountLTE(v int) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.FieldLTE(FieldGiftCount, v))
}

// HasPlayer applies the HasEdge predicate on the "player" edge.
func HasPlayer() predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlayerTable, PlayerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlayerWith applies the HasEdge predicate on the "player" edge with a given conditions (other predicates).
func HasPlayerWith(preds ...predicate.Player) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := newPlayerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasNpc applies the HasEdge predicate on the "npc" edge.
func HasNpc() predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, NpcTable, NpcColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasNpcWith applies the HasEdge predicate on the "npc" edge with a given conditions (other predicates).
func HasNpcWith(preds ...predicate.NPC) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(func(s *sql.Selector) {
		step := newNpcStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PlayerNPCRelationship) predicate.PlayerNPCRelationship {
	return predicate.PlayerNPCRelationship(sql.NotPredicates(p))
}
