// Code generated by ent, DO NOT EDIT.

package item

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the item type in the database.
	Label = "item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldItemID holds the string denoting the item_id field in the database.
	FieldItemID = "item_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldRarity holds the string denoting the rarity field in the database.
	FieldRarity = "rarity"
	// FieldBaseTrustValue holds the string denoting the base_trust_value field in the database.
	FieldBaseTrustValue = "base_trust_value"
	// FieldQuestItem holds the string denoting the quest_item field in the database.
	FieldQuestItem = "quest_item"
	// EdgeInventoryItems holds the string denoting the inventory_items edge name in mutations.
	EdgeInventoryItems = "inventory_items"
	// Table holds the table name of the item in the database.
	Table = "items"
	// InventoryItemsTable is the table that holds the inventory_items relation/edge.
	InventoryItemsTable = "inventory_items"
	// InventoryItemsInverseTable is the table name for the InventoryItem entity.
	// It exists in this package in order to avoid circular dependency with the "inventoryitem" package.
	InventoryItemsInverseTable = "inventory_items"
	// InventoryItemsColumn is the table column denoting the inventory_items relation/edge.
	InventoryItemsColumn = "item_inventory_items"
)

// Columns holds all SQL columns for item fields.
var Columns = []string{
	FieldID,
	FieldItemID,
	FieldName,
	FieldRarity,
	FieldBaseTrustValue,
	FieldQuestItem,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	ItemIDValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// RarityValidator is a validator for the "rarity" field. It is called by the builders before save.
	RarityValidator func(string) error
	// DefaultBaseTrustValue holds the default value on creation for the "base_trust_value" field.
	DefaultBaseTrustValue float64
	// DefaultQuestItem holds the default value on creation for the "quest_item" field.
	DefaultQuestItem bool
)

// OrderOption defines the ordering options for the Item queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByItemID orders the results by the item_id field.
func ByItemID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldItemID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByRarity orders the results by the rarity field.
func ByRarity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRarity, opts...).ToFunc()
}

// ByBaseTrustValue orders the results by the base_trust_value field.
func ByBaseTrustValue(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseTrustValue, opts...).ToFunc()
}

// ByQuestItem orders the results by the quest_item field.
func ByQuestItem(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuestItem, opts...).ToFunc()
}

// ByInventoryItemsCount orders the results by inventory_items count.
func ByInventoryItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newInventoryItemsStep(), opts...)
	}
}

// ByInventoryItems orders the results by inventory_items terms.
func ByInventoryItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newInventoryItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newInventoryItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(InventoryItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, InventoryItemsTable, InventoryItemsColumn),
	)
}
