// Code generated by ent, DO NOT EDIT.

package item

import (
	"agentic-npc-backend/internal/db/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldID, id))
}

// ItemID applies equality check predicate on the "item_id" field. It's identical to ItemIDEQ.
func ItemID(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldItemID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldName, v))
}

// Rarity applies equality check predicate on the "rarity" field. It's identical to RarityEQ.
func Rarity(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldRarity, v))
}

// BaseTrustValue applies equality check predicate on the "base_trust_value" field. It's identical to BaseTrustValueEQ.
func BaseTrustValue(v float64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldBaseTrustValue, v))
}

// QuestItem applies equality check predicate on the "quest_item" field. It's identical to QuestItemEQ.
func QuestItem(v bool) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldQuestItem, v))
}

// ItemIDEQ applies the EQ predicate on the "item_id" field.
func ItemIDEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldItemID, v))
}

// ItemIDNEQ applies the NEQ predicate on the "item_id" field.
func ItemIDNEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldItemID, v))
}

// ItemIDIn applies the In predicate on the "item_id" field.
func ItemIDIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldItemID, vs...))
}

// ItemIDNotIn applies the NotIn predicate on the "item_id" field.
func ItemIDNotIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldItemID, vs...))
}

// ItemIDGT applies the GT predicate on the "item_id" field.
func ItemIDGT(v string) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldItemID, v))
}

// ItemIDGTE applies the GTE predicate on the "item_id" field.
func ItemIDGTE(v string) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldItemID, v))
}

// ItemIDLT applies the LT predicate on the "item_id" field.
func ItemIDLT(v string) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldItemID, v))
}

// ItemIDLTE applies the LTE predicate on the "item_id" field.
func ItemIDLTE(v string) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldItemID, v))
}

// ItemIDContains applies the Contains predicate on the "item_id" field.
func ItemIDContains(v string) predicate.Item {
	return predicate.Item(sql.FieldContains(FieldItemID, v))
}

// ItemIDHasPrefix applies the HasPrefix predicate on the "item_id" field.
func ItemIDHasPrefix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasPrefix(FieldItemID, v))
}

// ItemIDHasSuffix applies the HasSuffix predicate on the "item_id" field.
func ItemIDHasSuffix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasSuffix(FieldItemID, v))
}

// ItemIDEqualFold applies the EqualFold predicate on the "item_id" field.
func ItemIDEqualFold(v string) predicate.Item {
	return predicate.Item(sql.FieldEqualFold(FieldItemID, v))
}

// ItemIDContainsFold applies the ContainsFold predicate on the "item_id" field.
func ItemIDContainsFold(v string) predicate.Item {
	return predicate.Item(sql.FieldContainsFold(FieldItemID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Item {
	return predicate.Item(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Item {
	return predicate.Item(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Item {
	return predicate.Item(sql.FieldContainsFold(FieldName, v))
}

// RarityEQ applies the EQ predicate on the "rarity" field.
func RarityEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldRarity, v))
}

// RarityNEQ applies the NEQ predicate on the "rarity" field.
func RarityNEQ(v string) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldRarity, v))
}

// RarityIn applies the In predicate on the "rarity" field.
func RarityIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldRarity, vs...))
}

// RarityNotIn applies the NotIn predicate on the "rarity" field.
func RarityNotIn(vs ...string) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldRarity, vs...))
}

// RarityGT applies the GT predicate on the "rarity" field.
func RarityGT(v string) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldRarity, v))
}

// RarityGTE applies the GTE predicate on the "rarity" field.
func RarityGTE(v string) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldRarity, v))
}

// RarityLT applies the LT predicate on the "rarity" field.
func RarityLT(v string) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldRarity, v))
}

// RarityLTE applies the LTE predicate on the "rarity" field.
func RarityLTE(v string) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldRarity, v))
}

// RarityContains applies the Contains predicate on the "rarity" field.
func RarityContains(v string) predicate.Item {
	return predicate.Item(sql.FieldContains(FieldRarity, v))
}

// RarityHasPrefix applies the HasPrefix predicate on the "rarity" field.
func RarityHasPrefix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasPrefix(FieldRarity, v))
}

// RarityHasSuffix applies the HasSuffix predicate on the "rarity" field.
func RarityHasSuffix(v string) predicate.Item {
	return predicate.Item(sql.FieldHasSuffix(FieldRarity, v))
}

// RarityEqualFold applies the EqualFold predicate on the "rarity" field.
func RarityEqualFold(v string) predicate.Item {
	return predicate.Item(sql.FieldEqualFold(FieldRarity, v))
}

// RarityContainsFold applies the ContainsFold predicate on the "rarity" field.
func RarityContainsFold(v string) predicate.Item {
	return predicate.Item(sql.FieldContainsFold(FieldRarity, v))
}

// BaseTrustValueEQ applies the EQ predicate on the "base_trust_value" field.
func BaseTrustValueEQ(v float64) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldBaseTrustValue, v))
}

// BaseTrustValueNEQ applies the NEQ predicate on the "base_trust_value" field.
func BaseTrustValueNEQ(v float64) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldBaseTrustValue, v))
}

// BaseTrustValueIn applies the In predicate on the "base_trust_value" field.
func BaseTrustValueIn(vs ...float64) predicate.Item {
	return predicate.Item(sql.FieldIn(FieldBaseTrustValue, vs...))
}

// BaseTrustValueNotIn applies the NotIn predicate on the "base_trust_value" field.
func BaseTrustValueNotIn(vs ...float64) predicate.Item {
	return predicate.Item(sql.FieldNotIn(FieldBaseTrustValue, vs...))
}

// BaseTrustValueGT applies the GT predicate on the "base_trust_value" field.
func BaseTrustValueGT(v float64) predicate.Item {
	return predicate.Item(sql.FieldGT(FieldBaseTrustValue, v))
}

// BaseTrustValueGTE applies the GTE predicate on the "base_trust_value" field.
func BaseTrustValueGTE(v float64) predicate.Item {
	return predicate.Item(sql.FieldGTE(FieldBaseTrustValue, v))
}

// BaseTrustValueLT applies the LT predicate on the "base_trust_value" field.
func BaseTrustValueLT(v float64) predicate.Item {
	return predicate.Item(sql.FieldLT(FieldBaseTrustValue, v))
}

// BaseTrustValueLTE applies the LTE predicate on the "base_trust_value" field.
func BaseTrustValueLTE(v float64) predicate.Item {
	return predicate.Item(sql.FieldLTE(FieldBaseTrustValue, v))
}

// QuestItemEQ applies the EQ predicate on the "quest_item" field.
func QuestItemEQ(v bool) predicate.Item {
	return predicate.Item(sql.FieldEQ(FieldQuestItem, v))
}

// QuestItemNEQ applies the NEQ predicate on the "quest_item" field.
func QuestItemNEQ(v bool) predicate.Item {
	return predicate.Item(sql.FieldNEQ(FieldQuestItem, v))
}

// HasInventoryItems applies the HasEdge predicate on the "inventory_items" edge.
func HasInventoryItems() predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, InventoryItemsTable, InventoryItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasInventoryItemsWith applies the HasEdge predicate on the "inventory_items" edge with a given conditions (other predicates).
func HasInventoryItemsWith(preds ...predicate.InventoryItem) predicate.Item {
	return predicate.Item(func(s *sql.Selector) {
		step := newInventoryItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Item) predicate.Item {
	return predicate.Item(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Item) predicate.Item {
	return predicate.Item(sql.NotPredicates(p))
}
