// Code generated by ent, DO NOT EDIT.

package memory

import (
	"agentic-npc-backend/internal/db/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCreatedAt, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldDescription, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldEventType, v))
}

// Importance applies equality check predicate on the "importance" field. It's identical to ImportanceEQ.
func Importance(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldImportance, v))
}

// Actor applies equality check predicate on the "actor" field. It's identical to ActorEQ.
func Actor(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldActor, v))
}

// Subject applies equality check predicate on the "subject" field. It's identical to SubjectEQ.
func Subject(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldSubject, v))
}

// Intensity applies equality check predicate on the "intensity" field. It's identical to IntensityEQ.
func Intensity(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldIntensity, v))
}

// Count applies equality check predicate on the "count" field. It's identical to CountEQ.
func Count(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCount, v))
}

// Harmful applies equality check predicate on the "harmful" field. It's identical to HarmfulEQ.
func Harmful(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldHarmful, v))
}

// Forgiven applies equality check predicate on the "forgiven" field. It's identical to ForgivenEQ.
func Forgiven(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldForgiven, v))
}

// Betrayal applies equality check predicate on the "betrayal" field. It's identical to BetrayalEQ.
func Betrayal(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldBetrayal, v))
}

// Text applies equality check predicate on the "text" field. It's identical to TextEQ.
func Text(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldText, v))
}

// FirstAt applies equality check predicate on the "first_at" field. It's identical to FirstAtEQ.
func FirstAt(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldFirstAt, v))
}

// LastAt applies equality check predicate on the "last_at" field. It's identical to LastAtEQ.
func LastAt(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldLastAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldCreatedAt, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldDescription, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldEventType, v))
}

// ImportanceEQ applies the EQ predicate on the "importance" field.
func ImportanceEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldImportance, v))
}

// ImportanceNEQ applies the NEQ predicate on the "importance" field.
func ImportanceNEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldImportance, v))
}

// ImportanceIn applies the In predicate on the "importance" field.
func ImportanceIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldImportance, vs...))
}

// ImportanceNotIn applies the NotIn predicate on the "importance" field.
func ImportanceNotIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldImportance, vs...))
}

// ImportanceGT applies the GT predicate on the "importance" field.
func ImportanceGT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldImportance, v))
}

// ImportanceGTE applies the GTE predicate on the "importance" field.
func ImportanceGTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldImportance, v))
}

// ImportanceLT applies the LT predicate on the "importance" field.
func ImportanceLT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldImportance, v))
}

// ImportanceLTE applies the LTE predicate on the "importance" field.
func ImportanceLTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldImportance, v))
}

// ActorEQ applies the EQ predicate on the "actor" field.
func ActorEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldActor, v))
}

// ActorNEQ applies the NEQ predicate on the "actor" field.
func ActorNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldActor, v))
}

// ActorIn applies the In predicate on the "actor" field.
func ActorIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldActor, vs...))
}

// ActorNotIn applies the NotIn predicate on the "actor" field.
func ActorNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldActor, vs...))
}

// ActorGT applies the GT predicate on the "actor" field.
func ActorGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldActor, v))
}

// ActorGTE applies the GTE predicate on the "actor" field.
func ActorGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldActor, v))
}

// ActorLT applies the LT predicate on the "actor" field.
func ActorLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldActor, v))
}

// ActorLTE applies the LTE predicate on the "actor" field.
func ActorLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldActor, v))
}

// ActorContains applies the Contains predicate on the "actor" field.
func ActorContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldActor, v))
}

// ActorHasPrefix applies the HasPrefix predicate on the "actor" field.
func ActorHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldActor, v))
}

// ActorHasSuffix applies the HasSuffix predicate on the "actor" field.
func ActorHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldActor, v))
}

// ActorEqualFold applies the EqualFold predicate on the "actor" field.
func ActorEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldActor, v))
}

// ActorContainsFold applies the ContainsFold predicate on the "actor" field.
func ActorContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldActor, v))
}

// SubjectEQ applies the EQ predicate on the "subject" field.
func SubjectEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldSubject, v))
}

// SubjectNEQ applies the NEQ predicate on the "subject" field.
func SubjectNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldSubject, v))
}

// SubjectIn applies the In predicate on the "subject" field.
func SubjectIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldSubject, vs...))
}

// SubjectNotIn applies the NotIn predicate on the "subject" field.
func SubjectNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldSubject, vs...))
}

// SubjectGT applies the GT predicate on the "subject" field.
func SubjectGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldSubject, v))
}

// SubjectGTE applies the GTE predicate on the "subject" field.
func SubjectGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldSubject, v))
}

// SubjectLT applies the LT predicate on the "subject" field.
func SubjectLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldSubject, v))
}

// SubjectLTE applies the LTE predicate on the "subject" field.
func SubjectLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldSubject, v))
}

// SubjectContains applies the Contains predicate on the "subject" field.
func SubjectContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldSubject, v))
}

// SubjectHasPrefix applies the HasPrefix predicate on the "subject" field.
func SubjectHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldSubject, v))
}

// SubjectHasSuffix applies the HasSuffix predicate on the "subject" field.
func SubjectHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldSubject, v))
}

// SubjectEqualFold applies the EqualFold predicate on the "subject" field.
func SubjectEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldSubject, v))
}

// SubjectContainsFold applies the ContainsFold predicate on the "subject" field.
func SubjectContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldSubject, v))
}

// DeltaIsNil applies the IsNil predicate on the "delta" field.
func DeltaIsNil() predicate.Memory {
	return predicate.Memory(sql.FieldIsNull(FieldDelta))
}

// DeltaNotNil applies the NotNil predicate on the "delta" field.
func DeltaNotNil() predicate.Memory {
	return predicate.Memory(sql.FieldNotNull(FieldDelta))
}

// IntensityEQ applies the EQ predicate on the "intensity" field.
func IntensityEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldIntensity, v))
}

// IntensityNEQ applies the NEQ predicate on the "intensity" field.
func IntensityNEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldIntensity, v))
}

// IntensityIn applies the In predicate on the "intensity" field.
func IntensityIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldIntensity, vs...))
}

// IntensityNotIn applies the NotIn predicate on the "intensity" field.
func IntensityNotIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldIntensity, vs...))
}

// IntensityGT applies the GT predicate on the "intensity" field.
func IntensityGT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldIntensity, v))
}

// IntensityGTE applies the GTE predicate on the "intensity" field.
func IntensityGTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldIntensity, v))
}

// IntensityLT applies the LT predicate on the "intensity" field.
func IntensityLT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldIntensity, v))
}

// IntensityLTE applies the LTE predicate on the "intensity" field.
func IntensityLTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldIntensity, v))
}

// CountEQ applies the EQ predicate on the "count" field.
func CountEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldCount, v))
}

// CountNEQ applies the NEQ predicate on the "count" field.
func CountNEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldCount, v))
}

// CountIn applies the In predicate on the "count" field.
func CountIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldCount, vs...))
}

// CountNotIn applies the NotIn predicate on the "count" field.
func CountNotIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldCount, vs...))
}

// CountGT applies the GT predicate on the "count" field.
func CountGT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldCount, v))
}

// CountGTE applies the GTE predicate on the "count" field.
func CountGTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldCount, v))
}

// CountLT applies the LT predicate on the "count" field.
func CountLT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldCount, v))
}

// CountLTE applies the LTE predicate on the "count" field.
func CountLTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldCount, v))
}

// HarmfulEQ applies the EQ predicate on the "harmful" field.
func HarmfulEQ(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldHarmful, v))
}

// HarmfulNEQ applies the NEQ predicate on the "harmful" field.
func HarmfulNEQ(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldHarmful, v))
}

// ForgivenEQ applies the EQ predicate on the "forgiven" field.
func ForgivenEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldForgiven, v))
}

// ForgivenNEQ applies the NEQ predicate on the "forgiven" field.
func ForgivenNEQ(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldForgiven, v))
}

// ForgivenIn applies the In predicate on the "forgiven" field.
func ForgivenIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldForgiven, vs...))
}

// ForgivenNotIn applies the NotIn predicate on the "forgiven" field.
func ForgivenNotIn(vs ...float64) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldForgiven, vs...))
}

// ForgivenGT applies the GT predicate on the "forgiven" field.
func ForgivenGT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldForgiven, v))
}

// ForgivenGTE applies the GTE predicate on the "forgiven" field.
func ForgivenGTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldForgiven, v))
}

// ForgivenLT applies the LT predicate on the "forgiven" field.
func ForgivenLT(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldForgiven, v))
}

// ForgivenLTE applies the LTE predicate on the "forgiven" field.
func ForgivenLTE(v float64) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldForgiven, v))
}

// BetrayalEQ applies the EQ predicate on the "betrayal" field.
func BetrayalEQ(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldBetrayal, v))
}

// BetrayalNEQ applies the NEQ predicate on the "betrayal" field.
func BetrayalNEQ(v bool) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldBetrayal, v))
}

// TextEQ applies the EQ predicate on the "text" field.
func TextEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldText, v))
}

// TextNEQ applies the NEQ predicate on the "text" field.
func TextNEQ(v string) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldText, v))
}

// TextIn applies the In predicate on the "text" field.
func TextIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldText, vs...))
}

// TextNotIn applies the NotIn predicate on the "text" field.
func TextNotIn(vs ...string) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldText, vs...))
}

// TextGT applies the GT predicate on the "text" field.
func TextGT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldText, v))
}

// TextGTE applies the GTE predicate on the "text" field.
func TextGTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldText, v))
}

// TextLT applies the LT predicate on the "text" field.
func TextLT(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldText, v))
}

// TextLTE applies the LTE predicate on the "text" field.
func TextLTE(v string) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldText, v))
}

// TextContains applies the Contains predicate on the "text" field.
func TextContains(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContains(FieldText, v))
}

// TextHasPrefix applies the HasPrefix predicate on the "text" field.
func TextHasPrefix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasPrefix(FieldText, v))
}

// TextHasSuffix applies the HasSuffix predicate on the "text" field.
func TextHasSuffix(v string) predicate.Memory {
	return predicate.Memory(sql.FieldHasSuffix(FieldText, v))
}

// TextEqualFold applies the EqualFold predicate on the "text" field.
func TextEqualFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldEqualFold(FieldText, v))
}

// TextContainsFold applies the ContainsFold predicate on the "text" field.
func TextContainsFold(v string) predicate.Memory {
	return predicate.Memory(sql.FieldContainsFold(FieldText, v))
}

// FirstAtEQ applies the EQ predicate on the "first_at" field.
func FirstAtEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldFirstAt, v))
}

// FirstAtNEQ applies the NEQ predicate on the "first_at" field.
func FirstAtNEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldFirstAt, v))
}

// FirstAtIn applies the In predicate on the "first_at" field.
func FirstAtIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldFirstAt, vs...))
}

// FirstAtNotIn applies the NotIn predicate on the "first_at" field.
func FirstAtNotIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldFirstAt, vs...))
}

// FirstAtGT applies the GT predicate on the "first_at" field.
func FirstAtGT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldFirstAt, v))
}

// FirstAtGTE applies the GTE predicate on the "first_at" field.
func FirstAtGTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldFirstAt, v))
}

// FirstAtLT applies the LT predicate on the "first_at" field.
func FirstAtLT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldFirstAt, v))
}

// FirstAtLTE applies the LTE predicate on the "first_at" field.
func FirstAtLTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldFirstAt, v))
}

// LastAtEQ applies the EQ predicate on the "last_at" field.
func LastAtEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldEQ(FieldLastAt, v))
}

// LastAtNEQ applies the NEQ predicate on the "last_at" field.
func LastAtNEQ(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNEQ(FieldLastAt, v))
}

// LastAtIn applies the In predicate on the "last_at" field.
func LastAtIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldIn(FieldLastAt, vs...))
}

// LastAtNotIn applies the NotIn predicate on the "last_at" field.
func LastAtNotIn(vs ...time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldNotIn(FieldLastAt, vs...))
}

// LastAtGT applies the GT predicate on the "last_at" field.
func LastAtGT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGT(FieldLastAt, v))
}

// LastAtGTE applies the GTE predicate on the "last_at" field.
func LastAtGTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldGTE(FieldLastAt, v))
}

// LastAtLT applies the LT predicate on the "last_at" field.
func LastAtLT(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLT(FieldLastAt, v))
}

// LastAtLTE applies the LTE predicate on the "last_at" field.
func LastAtLTE(v time.Time) predicate.Memory {
	return predicate.Memory(sql.FieldLTE(FieldLastAt, v))
}

// CoversIsNil applies the IsNil predicate on the "covers" field.
func CoversIsNil() predicate.Memory {
	return predicate.Memory(sql.FieldIsNull(FieldCovers))
}

// CoversNotNil applies the NotNil predicate on the "covers" field.
func CoversNotNil() predicate.Memory {
	return predicate.Memory(sql.FieldNotNull(FieldCovers))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Memory {
	return predicate.Memory(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.NPC) predicate.Memory {
	return predicate.Memory(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Memory) predicate.Memory {
	return predicate.Memory(sql.NotPredicates(p))
}
