// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemoriesColumns holds the columns for the "memories" table.
	MemoriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "description", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "participants", Type: field.TypeJSON},
		{Name: "importance", Type: field.TypeFloat64, Default: 0.5},
		{Name: "npc_memories", Type: field.TypeUUID},
	}
	// MemoriesTable holds the schema information for the "memories" table.
	MemoriesTable = &schema.Table{
		Name:       "memories",
		Columns:    MemoriesColumns,
		PrimaryKey: []*schema.Column{MemoriesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "memories_np_cs_memories",
				Columns:    []*schema.Column{MemoriesColumns[6]},
				RefColumns: []*schema.Column{NpCsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// NpCsColumns holds the columns for the "np_cs" table.
	NpCsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "npc_type", Type: field.TypeString, Default: "villager"},
		{Name: "emotions", Type: field.TypeJSON},
		{Name: "current_goals", Type: field.TypeJSON, Nullable: true},
	}
	// NpCsTable holds the schema information for the "np_cs" table.
	NpCsTable = &schema.Table{
		Name:       "np_cs",
		Columns:    NpCsColumns,
		PrimaryKey: []*schema.Column{NpCsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemoriesTable,
		NpCsTable,
	}
)

func init() {
	MemoriesTable.ForeignKeys[0].RefTable = NpCsTable
}
