# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ai_pb2 as ai__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ai_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AIBrainStub(object):
    """The AIBrain service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Think = channel.unary_unary(
                '/ai.AIBrain/Think',
                request_serializer=ai__pb2.EventRequest.SerializeToString,
                response_deserializer=ai__pb2.ActionResponse.FromString,
                _registered_method=True)
        self.ThinkStream = channel.unary_stream(
                '/ai.AIBrain/ThinkStream',
                request_serializer=ai__pb2.EventRequest.SerializeToString,
                response_deserializer=ai__pb2.TokenChunk.FromString,
                _registered_method=True)


class AIBrainServicer(object):
    """The AIBrain service definition.
    """

    def Think(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ThinkStream(self, request, context):
        """ThinkStream streams the response token-by-token (C3). The RAG path streams real
        LLM tokens; other paths yield their whole answer as a single chunk. Unary Think is
        kept for compatibility and as the non-streaming fallback.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIBrainServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Think': grpc.unary_unary_rpc_method_handler(
                    servicer.Think,
                    request_deserializer=ai__pb2.EventRequest.FromString,
                    response_serializer=ai__pb2.ActionResponse.SerializeToString,
            ),
            'ThinkStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ThinkStream,
                    request_deserializer=ai__pb2.EventRequest.FromString,
                    response_serializer=ai__pb2.TokenChunk.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ai.AIBrain', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ai.AIBrain', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AIBrain(object):
    """The AIBrain service definition.
    """

    @staticmethod
    def Think(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ai.AIBrain/Think',
            ai__pb2.EventRequest.SerializeToString,
            ai__pb2.ActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ThinkStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ai.AIBrain/ThinkStream',
            ai__pb2.EventRequest.SerializeToString,
            ai__pb2.TokenChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
