// Code generated by ent, DO NOT EDIT.

package quest

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the quest type in the database.
	Label = "quest"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldStaticDataPath holds the string denoting the static_data_path field in the database.
	FieldStaticDataPath = "static_data_path"
	// EdgePlayerQuestStates holds the string denoting the player_quest_states edge name in mutations.
	EdgePlayerQuestStates = "player_quest_states"
	// Table holds the table name of the quest in the database.
	Table = "quests"
	// PlayerQuestStatesTable is the table that holds the player_quest_states relation/edge.
	PlayerQuestStatesTable = "player_quest_states"
	// PlayerQuestStatesInverseTable is the table name for the PlayerQuestState entity.
	// It exists in this package in order to avoid circular dependency with the "playerqueststate" package.
	PlayerQuestStatesInverseTable = "player_quest_states"
	// PlayerQuestStatesColumn is the table column denoting the player_quest_states relation/edge.
	PlayerQuestStatesColumn = "quest_player_quest_states"
)

// Columns holds all SQL columns for quest fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldStaticDataPath,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// StaticDataPathValidator is a validator for the "static_data_path" field. It is called by the builders before save.
	StaticDataPathValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the Quest queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByStaticDataPath orders the results by the static_data_path field.
func ByStaticDataPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStaticDataPath, opts...).ToFunc()
}

// ByPlayerQuestStatesCount orders the results by player_quest_states count.
func ByPlayerQuestStatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPlayerQuestStatesStep(), opts...)
	}
}

// ByPlayerQuestStates orders the results by player_quest_states terms.
func ByPlayerQuestStates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPlayerQuestStatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPlayerQuestStatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PlayerQuestStatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PlayerQuestStatesTable, PlayerQuestStatesColumn),
	)
}
